---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teleport
spec:
  interval: 30m
  chart:
    spec:
      chart: teleport-cluster
      version: 16.4.7
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    clusterName: teleport.gddnet.io
    chartMode: standalone
    kubeClusterName: gdd-talos
    validateConfigOnDeploy: true
    enterprise: false
    auth:
      annotations:
        deployment:
          reloader.stakater.com/auto: "true"
      teleportConfig:
        auth_service:
          client_idle_timeout: 2h
          client_idle_timeout_message: "Connection closed after 2hours without activity"
          session_recording: "node-sync"
    proxy:
      annotations:
        deployment:
          reloader.stakater.com/auto: "true"
      teleportConfig:
        proxy_service:
          trust_x_forwarded_for: true
    podSecurityPolicy:
      enabled: true
    log:
      level: INFO
      output: stderr
      format: text
      extraFields: ["timestamp", "level", "component", "caller"]
    ingress:
      enabled: true
      suppressAutomaticWildcards: false
      spec:
        ingressClassName: external
    annotations:
      ingress:
        external-dns.alpha.kubernetes.io/target: "external.gddnet.io"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "https"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    authentication:
      type: local
    proxyListenerMode: multiplex
    persistence:
      enabled: true
    serviceAccount:
      create: true
    rbac:
      create: true
    service:
      type: ClusterIP
