---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-jellyseerr
  namespace: plex
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: RESTIC_REPOSITORY
    remoteRef:
      key: "d755d2d8-b892-45a6-b0ea-b2260012dffd"
  - secretKey: RESTIC_PASSWORD
    remoteRef:
      key: "9bf71699-10c2-44c5-a4f5-b226001272e7"
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: "262aa999-35f6-4bc9-bb8d-b2260012965c"
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: "29f10e7a-0211-4e92-b245-b2260012b30d"
  target:
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}${NS}/${APP}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"

