
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: jarvis
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: FRIGATE_MQTT_PASSWORD
    remoteRef:
      key: "e65ecd87-6469-4539-9ae3-b2190143a424"
  - secretKey: FRIGATE_MQTT_USER
    remoteRef:
      key: "649b3aca-eb9b-4a69-b25b-b219014387b7"
  - secretKey: FRIGATE_RTSP_USER
    remoteRef:
      key: "51ad6e55-6252-446b-9040-b2190143cd19"
  - secretKey: FRIGATE_RTSP_PASSWORD
    remoteRef:
      key: "041df2ef-be15-4048-90c9-b22101544974"
  - secretKey: PLUS_API_KEY
    remoteRef:
      key: "3e7322ff-5ace-4531-9009-b24f008063ab"