---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app frigate
  namespace: jarvis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: emqx
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      frigate:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.16.0
            env:
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: frigate
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 8Gi
        pod:
          nodeSelector:
            google.feature.node.kubernetes.io/coral: "true"
#            intel.feature.node.kubernetes.io/gpu: "true"

    service:
      app:
        controller: frigate
        annotations:
          teleport.dev/name: *app
        labels:
          teleport: enabled
        ports:
          http:
            port: 5000
          rtsp:
            port: 8554
    ingress:
      frigate:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.gddnet.io"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home Automation
          gethomepage.dev/name: Frigate
          gethomepage.dev/icon: frigate.svg

        hosts:
          - host: frigate.int.gddnet.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      frigateconfig:
        existingClaim: frigate-config
        advancedMounts:
          frigate:
            app:
              - path: /config
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 6Gi
        globalMounts:
          - path: /dev/shm
      usb:
        type: hostPath
        hostPath: /dev/bus/usb
        hostPathType: Directory
        globalMounts:
          - path: /dev/bus/usb
      media:
        existingClaim: frigate-media
