---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-b2
  namespace: database
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: ACCESS_KEY_ID
    remoteRef:
      key: "0d408eae-142c-4947-ba64-b38601426e3b"
  - secretKey: ACCESS_SECRET_KEY
    remoteRef:
      key: "11ce4859-90d2-4501-ac01-b3860142ab16"
  target:
    name: postgres-b2
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .ACCESS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .ACCESS_SECRET_KEY }}"
