---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: b2-store
  namespace: database
spec:
  configuration:
    destinationPath: s3://omni-talos-gdd/database/postgres
    endpointURL: https://s3.us-west-000.backblazeb2.com
    s3Credentials:
      accessKeyId:
        name: postgres-b2
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: postgres-b2
        key: ACCESS_SECRET_KEY
    wal:
      compression: zstd
    data:
      compression: gzip
  retentionPolicy: "30d"