# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: stash-fileflows-sync-secret
stringData:
    STASH_API_KEY: ENC[AES256_GCM,data:bMxPgswqkP7CEALa9vWn1us28bm8YfPdIa2KGLHbSFJ0FkdyIGhMlBix7hmEqhSi8dyEZa5o0nuy+3IJadYBVY0y6W1icpXUsDtt8zldbFJd0Qy+fNI94V8vbbHsRwFIvCyoFmvay3lKY435gSeUeNSiAtdiKuu37t9/rrEHa5E1RD786bYn8eLRJwwmzJXu5MyqC+gqrau9WKRQLioJ,iv:NitDXnRE4VyWIJu/DqKmQ105YIyNlT5JLFQDBkP9rGQ=,tag:k3D5EXu4blgptc+cPVEVbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbmtYeTJ5NUxsaXpLNWJY
            eU04Yk9RdjhVOEZvS1pBR3g5V0dzU2loZGpVCkJpZnM5L0hScTVUd01hTGVDbTd2
            T2NINHBrVzMzbkFHTzNHRXRKZ0FUZFUKLS0tIDJ3UE5TQ3JvRnZBUGNtalpVaWdE
            S2RGRC93ZlNKVVd5Y0VqVzdJd3dSUXcKO0RD8MFk6cMlDCUkSf4EJGJWfEk3PRrb
            5W9FgQmvIsPVdie9xqccWAGsOZuDXylwrx/XrF7u0lpGHNxslD16jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T21:10:36Z"
    mac: ENC[AES256_GCM,data:LvV//ZDFf5XsUQ2PLCncvTgMNElO9EKw1O3JHEyX9VmjzhFEkvJ/2d71APYBSqyyZECCAUKsHogBb/mF04VXr+yEQfkmkiTyAx3SQIkpqpTDvds2R9utV2v+mHXcrN8s4fAW/9RZL1sOWuDDdy6SB41zyhPWwWx6V7wsgalRZFM=,iv:YArkda5o4Q4YjDixov0aTSJvUmiguI30NPQgdmL+a0Y=,tag:bKRrfNdyr+bsXzta5hTR0Q==,type:str]
    version: 3.13.3
