---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-vlan60
spec:
  config: |
    {
      "cniVersion": "1.1.0",
      "name": "multus-vlan60",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp6259326.60",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "addresses": [],
            "routes": [
              { "dst": "0.0.0.0/0", "gw": "10.0.60.1" }
            ]
          }
        },
        { "type": "sbr" }
      ]
    }
