---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-vlan60
spec:
  config: |
    {
      "cniVersion": "1.1.0",
      "name": "multus-vlan60",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp2da31d1.60",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "addresses": []
          }
        }
      ]
    }
