---
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PublicResource
metadata:
  name: rook-dashboard
spec:
  siteRef: homeops
  name: Ceph (Web)
  protocol: http
  fullDomain: rook.app.gddnet.io
  ssl: true
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/ceph.png
  resourcePolicyNiceId: thick-louisiana-waterthrush
  targets:
    - hostname: rook-ceph-mgr-dashboard.rook-ceph.svc.cluster.local
      port: 7000
      method: http
  auth:
    ssoEnabled: true
    ssoRoles:
      - Admin
