---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: linkwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "{{ .database_url }}"
        NEXTAUTH_SECRET: "{{ .nextauth_secret }}"
  data:
    - secretKey: database_url
      remoteRef:
        key: linkwarden-db-secret
        property: DATABASE_URL
    - secretKey: nextauth_secret
      remoteRef:
        key: linkwarden-auth-secret
        property: NEXTAUTH_SECRET
