---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/netbird.io/networkresource_v1alpha1.json
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: linkwarden
spec:
  networkRouterRef:
    name: homeops
    namespace: network
  serviceRef:
    name: linkwarden
  groups:
    - name: tier-family
