---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: bws_token
            name: bws-secrets
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: tls.crt
      organizationID: 2b964cb6-c641-436b-9fe8-b215014c4076
      projectID: 00e06f61-f9a2-4dbc-905a-b2150159484c