---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: database
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-system
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
