
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: HBOX_DATABASE_PASSWORD
    remoteRef:
      key: "b3fe5327-7ead-46dd-85f5-b3fd012398a7"

