
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: HBOX_DATABASE_PASSWORD
    remoteRef:
      key: "b3fe5327-7ead-46dd-85f5-b3fd012398a7"
  - secretKey: HBOX_OIDC_CLIENT_ID
    remoteRef:
      key: "b260ed0a-864d-4544-9a97-b3fd01379213"
  - secretKey: HBOX_OIDC_CLIENT_SECRET
    remoteRef:
      key: "fa54e673-fadb-4ca5-8510-b3fd0137a99d"
