apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-data
  namespace: service
  labels:
    homelab/usage: service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
---