---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - href: https://youtube.com/feed/subscriptions
    - Tech:
        - HackerNews:
            - href: https://news.ycombinator.com
        - Anandtech:
            - href: https://www.anandtech.com
        - Moronix:
            - href: https://www.phoronix.com
        - ServeTheHome:
            - href: https://www.servethehome.com
    - Social:

  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Calendar:
        # - Calendar:
        #     widget:
        #       type: calendar
        #       firstDayInWeek: sunday # optional - defaults to monday
        #       view: monthly # optional - possible values monthly, agenda
        #       maxEvents: 10 # optional - defaults to 10
        #       integrations: # optional
        #         - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Sonarr # service name for that widget
        #         - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Radarr # service name for that widget
        #         - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Readarr # service name for that
        - Agenda:
            widget:
              type: calendar
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 20 # optional - defaults to 10
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Plex # group name where widget exists
                  service_name: Sonarr # service name for that widget
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Plex # group name where widget exists
                  service_name: Radarr # service name for that widget

    - Infrastructure:
        - Unifi:
            href: https://unifi.${PRIVATE_DOMAIN}
            icon: unifi.png
            widget:
              type: unifi
              url: https://unifi.${PRIVATE_DOMAIN}
              username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
              password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
        - Proxmox:
            href: https://proxmox.${PRIVATE_DOMAIN}
            icon: proxmox.png
            widget:
              type: proxmox
              url: https://proxmox.${PRIVATE_DOMAIN}
              username: {{HOMEPAGE_VAR_PROXMOX_TOKEN_ID}}
              password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}

  settings.yaml: |
    title: Dashboard
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Calendar:
        style: columns
      Service:
        style: columns
      Home Automation:
        style: columns
      Plex:
        style: columns
        columns: 3
      Security:
        style: row
        columns: 2
      Games:
        style: row
      Infrastructure:
        style: row
        columns: 2
      Storage:
        style: row
        columns: 3
      Observability:
        style: row
        columns: 3
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: [brave, bing]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - openmeteo:
        label: Home
        units: metric
        cache: 5
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23