
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: HOMEPAGE_VAR_SONARR_TOKEN
    remoteRef:
      key: "f5a6a538-d353-4194-8006-b21d0188b04c"
  - secretKey: HOMEPAGE_VAR_RADARR_TOKEN
    remoteRef:
      key: "f5a6a538-d353-4194-8006-b21d0188b04c"
  - secretKey: HOMEPAGE_VAR_PLEX_TOKEN
    remoteRef:
      key: "6dffceaa-4eb8-4b12-91bb-b230012abd24"
  - secretKey: HOMEPAGE_VAR_QBIT_TOKEN
    remoteRef:
      key: "b215f012-3c57-406d-a3b2-b230012ae6c8"
  - secretKey: HOMEPAGE_VAR_GRAFANA_TOKEN
    remoteRef:
      key: "9dab32d8-7542-4be5-8a3b-b230012b70fb"
  - secretKey: HOMEPAGE_VAR_TAUTULLI_TOKEN
    remoteRef:
      key: "17947f59-f130-4ee4-8aec-b230012b3027"