
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: "8239790e-50e0-4498-b3df-b21b007fe74a"
  - secretKey: AUTHENTIK_POSTGRES__PASSWORD
    remoteRef:
      key: "b9dd5489-bba6-4f69-8c79-b21b0063d58e"
  - secretKey: HOMEPAGE_VAR_SONARR_TOKEN
    remoteRef:
      key: "f5a6a538-d353-4194-8006-b21d0188b04c"
  - secretKey: HOMEPAGE_VAR_RADARR_TOKEN
    remoteRef:
      key: "f5a6a538-d353-4194-8006-b21d0188b04c"
  - secretKey: HOMEPAGE_VAR_PROWLARR_TOKEN
    remoteRef:
      key: "cf85a113-53c6-4dcf-8b41-b21f00617e1f"
