---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zipline-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: zipline-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "{{ .database_url }}"
        CORE_SECRET: "{{ .core_secret }}"
  data:
    - secretKey: database_url
      remoteRef:
        key: zipline-db-secret
        property: DATABASE_URL
    - secretKey: core_secret
      remoteRef:
        key: zipline-core-secret
        property: CORE_SECRET
