---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: netbird-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "0.8.0"
  url: oci://ghcr.io/netbirdio/helm-charts/netbird-operator
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: netbird-operator
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    managementURL: https://access.gddnet.io

    cluster:
      name: homeops
      dns: svc.cluster.local

    netbirdAPI:
      keyFromSecret:
        name: netbird-mgmt-api-key
        key: NB_API_KEY

    webhook:

      enableCertManager: true
    gatewayAPI:
      enabled: true

    operator:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 512Mi
