apiVersion: v1
kind: Secret
metadata:
    name: netbird-mgmt-api-key
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:xBih9tEooonssNB2+Hba5qaQf4vobuQgQfZF5nI422R2HgEMKBl0aQ==,iv:F/BZZc/Em1Lxn8NR03j0kl4B3DzMRF84smcA2V43vok=,tag:eNC2SGSTupdXjWjHZGH1Sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQzk3UGFPcVdIVU9xbG1S
            eENPMStJeExtc0xLVGdhZGROZjlsUHR6ckIwCjR1c2UvWlFqVXJKRGhXREM0Kzhu
            Mlc2QVF2T1FSaVoxcnBWaEJwdm03bjgKLS0tIDFTUnNSWkZLTHFtUkpqU2c2QTVJ
            MHFuMGlVNThYcE5aNklUb2xONjkrMFkK5NrqlNx/e2A4lefLoe0nc7uJDcSnhWgp
            sul8EdBYYNavHGybgYu+i4k+ZVbKnYNK4aI2T5AWdH7znAN2Zv9JdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T07:05:05Z"
    mac: ENC[AES256_GCM,data:+KJzwa+yBXr0JOLTovY7BYA6gr0qARNvvenYulHrmMyhJdFUjUK9OSvhjHd7JMMSnII/E/7J6RSWn5Ny9In5vAO6OAOeUBRUeaRy6dPlyucHR8ZYk8Z9fjD2WK3c+147WeQs+fDC2DI3gJJ5iFBQOoh0qFrUCYK+4PeTv5I4KkU=,iv:A20gdG3jeWbAmejGlyQGLiSfzXEhIDQQZXO/sjMyS8A=,tag:53Ue3I+Orpe9oTG+iRmi3Q==,type:str]
    version: 3.13.3
