---
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PublicResource
metadata:
  name: zigbee2mqtt
spec:
  siteRef: homeops
  name: Zigbee2MQTT
  protocol: http
  fullDomain: zigbee.app.gddnet.io
  ssl: true
  targets:
    - hostname: zigbee2mqtt.gdd-jarvis.svc.cluster.local
      port: 8080
      method: http
      healthcheck:
        hostname: zigbee2mqtt.gdd-jarvis.svc.cluster.local
        port: 8080
        enabled: true
        scheme: http
        path: /
        interval: 30
        timeout: 5
        status: 200
  auth:
    ssoEnabled: true
    ssoRoles:
      - Admin
