---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./rook-ceph.yaml
  - ./external-secrets.yaml

  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./cloudnative-pg.yaml
  # - ./crossplane.yaml
  # - ./crunchydata.yaml
  # - ./csi-driver-nfs.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  - ./grafana.yaml
  - ./intel.yaml
  - ./kyverno.yaml
  - ./piraeus.yaml
  - ./stevehipwell.yaml
  - ./bitwarden.yaml
  - ./codecentric.yaml
  - ./node-feature-discovery.yaml
  - ./authentik.yaml
  - ./hashicorp.yaml
  - ./teleport.yaml
  - ./nextcloud.yaml
  - ./windmill.yaml
  - ./crowdsec.yaml