---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-relay-secret
  namespace: network
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: SMTP_RELAY_HOSTNAME
      remoteRef:
        key: "TODO-bitwarden-item-uuid" # e.g. relay.gddnet.io
    - secretKey: SMTP_RELAY_SERVER
      remoteRef:
        key: "TODO-bitwarden-item-uuid" # upstream smarthost address (e.g. smtp.your-provider.com)
    - secretKey: SMTP_RELAY_USERNAME
      remoteRef:
        key: "TODO-bitwarden-item-uuid"
    - secretKey: SMTP_RELAY_PASSWORD
      remoteRef:
        key: "TODO-bitwarden-item-uuid"
