---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 150Gi
  storageClassName: nfs-csi