---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ogamex-db-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: MARIADB_ROOT_PASSWORD
      remoteRef:
        key: "TODO-bitwarden-item-uuid-ogamex"
        property: DB_ROOT_PASSWORD
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: "TODO-bitwarden-item-uuid-ogamex"
        property: DB_PASSWORD
