# =============================================================================
# !! PLAINTEXT — ENCRYPT WITH SOPS BEFORE `git add` !!
#   sops --age age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y \
#        --encrypt --encrypted-regex '^(data|stringData)$' --in-place \
#        kubernetes/apps/gdd-game/ogamex-db/app/secret.sops.yaml
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: ogamex-db-secret
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:XNCw+SQCSLF5AP0ldIoHoNPGs8oX3+ISnfW8AYprapt2VA4YuIv9yG3Phf5sOI4W,iv:CBvEYWv5FUpNB58WgjwfEJs5U0qAN1vitzCgqd1rSbY=,tag:Ly3IWjT1QzJu3NUUsQf6gw==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:GvlO2wDRruj1YKWlRSXOLlxwHtSWYWopyodxTGuWXrqKn/QBUHBTTQLDjCnL7Obh,iv:9RKwHkDJgKIWn3RYK8NE08U9xrKIjh14l+Ogd2KogSk=,tag:FBsuW+95KT9B3/EafrMDZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRjgvQ3ErVnlRUUI0NW83
            aGduNVgwNW8vZG1JcmVUZUl6YTB5QVhuQ2tBCjBmZE0xUVhRL1FLUUhkNTdsVGk2
            aVlDSTRPbVRWMEFEY2Jvb2NMTmc5WWMKLS0tIE5NOElzWGVxb2JlQ0lVVlRkM04r
            VTBDNHJlZndyVW15bGF4WFNBbEYvalkKDJ4d9OBb9/jye8vQqNyXNzVN2R6if/XT
            DVRTZWl1I17wELzHaqHLc+fImmdZMHoNa8nbpcHDYE0fgxWwe5FvxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T18:26:33Z"
    mac: ENC[AES256_GCM,data:Qjuxvgf4wxNmhnabpkzoD4O61L60yjn0dVFh3CpaG/GPghv4Tbif/HoSGCHBSU2rm1A7hqpMxIm4XeDhMXPcTi0KGExA2vz/ikiLxU9OJMBtWIVbqZVg8UfwsAgA1OhBoJrjcMiZdGm/tN+5sKLnDDDh2LvW+ySSMFD9FZ355Uc=,iv:jWvBtmG8cz6pf34Lxkw9p3SBEkqv6zCumlDRykfodwA=,tag:shNfIULulTqt1mAGxr30lw==,type:str]
    version: 3.13.3
