---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 150Gi
  storageClassName: ceph-block
