# =============================================================================
# !! PLAINTEXT — ENCRYPT WITH SOPS BEFORE `git add` !!
#   sops --age age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y \
#        --encrypt --encrypted-regex '^(data|stringData)$' --in-place \
#        kubernetes/apps/gdd-service/actual/app/secret.sops.yaml
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: actual-authentik-oauth
stringData:
    ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:aqYUniDsZpIcfuZWrsgqTvhdbmLCBZ9gwHwAc/f+uqzAqSMlkyxtsg==,iv:wGGlgBb79mD5wxo/6reo2+QBSaJ0sItaA9YexkRN+MQ=,tag:Slc8g0C5ObBYTZzlDStfDg==,type:str]
    ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:cgWZXjiRwVpwjjay4fvbghhAGG+bBsWHOLGuHCtpZbfH+nKOOQtk+fAAB0Nh0iy4eD7NwmozsAdVHk6WeSTpeeJmKUorvQPJkgxIfubmYsX23R+51bYUwjpJmqOoIzgKISyq3QOzMxUF62icAz4qMQ/ZpDz2krvCG4qj3nqkBsU=,iv:hrHyzRm5yGWm25obZA0C3b9iWMjtdo4e+/ytqfML074=,tag:xnOXxbuTOb76Ybvr6af+AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYVlQMUQwMEtCSE4vWVlr
            Y1VETmYwRGJOaHVidGRPb041RDRVNU9zTWlZCnJvTitvR2cwMUJwemxuVnhjcFpJ
            bkhQeXpVUjljWm56bnhaR3g3TDFmSVUKLS0tIHhqV1daV1FuekM0L3oyQlFWcDQ5
            eFYxRUNnZU9ORDFSVnFtcVppMHJyVTAKsrvnQyBUpvS6MJ72LWy2xwCFbSA5oaoc
            3PKlsGaOWlPAbeixyMCDBLmsaRsAGzQa1G7dcDLvidoE81rP4fSt2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T06:17:43Z"
    mac: ENC[AES256_GCM,data:ZPR6VX/0omEpY5cbZi8MDzns2BNWr7tAgJviCY6EtjLKTfyX5R7pA+BuqLiMqeVJw5HWSJbVKtMka0xJOsy0CRW8CfBY09WrE6cGV1PvxRVD0SVFfqSys2UmgLcxZP8u/XrNP3ezSUSkWu8cYIb4RXQg6YlXw1NVqiHqQ8LrRsI=,iv:dq3Fc+QWVfN+6ZB3DyueKvl58PKc1bXUwil7mluibok=,tag:fQACs2JZNBCf3GPcjP0qug==,type:str]
    version: 3.13.3
