---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spoolman
  annotations:
    tailscale.com/proxy-group: ts-ingress
spec:
  ingressClassName: tailscale
  rules:
    - host: spoolman.barn-walleye.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spoolman
                port:
                  number: 8000
  tls:
    - hosts:
        - spoolman.barn-walleye.ts.net
