---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keepit-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: REDDIT_CLIENT_ID
      remoteRef:
        key: "05556c71-93bb-46e5-b5ad-b45e012519a1"
        property: REDDIT_CLIENT_ID
    - secretKey: REDDIT_CLIENT_SECRET
      remoteRef:
        key: "4a5f5d86-36c4-41a2-8914-b45e01253844"
        property: REDDIT_CLIENT_SECRET
    - secretKey: REDDIT_USERNAME
      remoteRef:
        key: "de280ef4-e9a3-48d8-955a-b45e0125527b"
        property: REDDIT_USERNAME
    - secretKey: REDDIT_PASSWORD
      remoteRef:
        key: "ddb97324-48dd-43e7-a75e-b45e01256c77"
        property: REDDIT_PASSWORD
