---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bambubuddy
  annotations:
    tailscale.com/proxy-group: ts-ingress
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "3D Printing"
    gethomepage.dev/name: BambuBuddy
    gethomepage.dev/icon: bambu-lab.svg
    gethomepage.dev/description: "Tailscale only | Bambu Lab companion"
    gethomepage.dev/siteMonitor: "http://bambubuddy.gdd-service.svc:8000"
spec:
  ingressClassName: tailscale
  rules:
    - host: bambubuddy.barn-walleye.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bambubuddy
                port:
                  number: 8000
  tls:
    - hosts:
        - bambubuddy.barn-walleye.ts.net
