---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: christmas-community-secret
  namespace: gdd-service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: GUEST_PASSWORD
      remoteRef:
        key: "TODO-bitwarden-item-uuid"
