---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app christmas-community
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      christmas-community:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/wingysam/christmas-community
              tag: "1.42.0"
            env:
              TZ: America/Chicago
              LANGUAGE: en-us
              SITE_TITLE: Wishlists
              SHORT_TITLE: Wishlists
              SMILE: "false"
              UPDATE_CHECK: "false"
              PORT: &port 8081
            envFrom:
              - secretRef:
                  name: christmas-community-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        annotations:
          pangolin-operator/site-ref: homeops
          pangolin-operator/name: Christmas Community
          pangolin-operator/full-domain: christmas-community.app.gddnet.io
          pangolin-operator/port: http
          pangolin-operator/auth-sso: "true"
          pangolin-operator/auth-sso-roles: Admin
          pangolin-operator/icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/christmas-community.png
          pangolin-operator/resource-policy: thick-louisiana-waterthrush
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
