---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: epicgames-secret
  namespace: gdd-service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: EMAIL
      remoteRef:
        key: "TODO-bitwarden-item-uuid" # Epic Games account email
    - secretKey: EMAIL_SENDER_ADDRESS
      remoteRef:
        key: "TODO-bitwarden-item-uuid"
    - secretKey: EMAIL_RECIPIENT_ADDRESS
      remoteRef:
        key: "TODO-bitwarden-item-uuid"
