
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secret
  namespace: gdd-development
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: ADMIN_USER
    remoteRef:
      key: "d4cb252b-a137-4267-87d7-b22c014bba1d"
