---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  labels:
    dragonflydb.io/cluster: dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.25.1@sha256:d40f3373dc65fa72a85df26194e99cd442bab741430e6c7f57456b0d7e2cdc88
  replicas: 3
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
    nodeSelector:
      feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
  serviceSpec:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: 10.0.32.8
      external-dns.alpha.kubernetes.io/hostname: redis.int.gddnet.io
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: dragonfly
  nodeSelector:
    feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
