---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kavita
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      kavita:
        strategy: RollingUpdate
        containers:
          kavita:
            image:
              repository: jvmilazz0/kavita
              tag: 0.8.6
            env:
              TZ: America/Chicago
              PUID: 1000
              PGID: 1000
              DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

    service:
      kavita:
        controller: kavita
        annotations:

        ports:
          http:
            port: 5000
    ingress:
      kavita:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.gddnet.io
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Service
          gethomepage.dev/name: kavita
          gethomepage.dev/icon: kavita.svg
        hosts:
          - host: book.gddnet.io
            paths:
              - path: /
                service:
                  identifier: kavita
                  port: http

    persistence:
      kavita-app:
        existingClaim: kavita-app
        advancedMounts:
          kavita:
            kavita:
              - path: /kavita/config
      kavita-books:
        existingClaim: kavita-books
        advancedMounts:
          kavita:
            kavita:
              - path: /books
