
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-local-volsync
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: VOLSYNC_LOCAL_RESTIC_PASSWORD
    remoteRef:
      key: "57657703-39e1-41a7-a226-b3860141f806"
  - secretKey: VOLSYNC_LOCAL_ACCESS_KEY_ID
    remoteRef:
      key: "072086ba-6674-4801-a2a7-b38601421aa1"
  - secretKey: VOLSYNC_LOCAL_BUCKET_ENDPOINT
    remoteRef:
      key: "be3c5c1a-1c6f-4e92-93e6-b38601422f4e"
  - secretKey: VOLSYNC_LOCAL_SECRET_ACCESS_KEY
    remoteRef:
      key: "25acb515-115c-435e-ad10-b3860142453b"
  target:
    template:
      engineVersion: v2
      data:
#        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}${NS}/${APP}"
        RESTIC_REPOSITORY: "{{ .VOLSYNC_LOCAL_BUCKET_ENDPOINT }}/volsync/${NS}/${APP}"
        RESTIC_PASSWORD: "{{ .VOLSYNC_LOCAL_RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .VOLSYNC_LOCAL_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .VOLSYNC_LOCAL_SECRET_ACCESS_KEY }}"