
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secret
  namespace: gdd-plex
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: api_key
    remoteRef:
      key: "f5a6a538-d353-4194-8006-b21d0188b04c"

