---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ferdium-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: ferdium-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_HOST: "{{ .db_host }}"
        DB_PORT: "{{ .db_port }}"
        DB_USER: "{{ .db_user }}"
        DB_PASSWORD: "{{ .db_password }}"
        DB_DATABASE: "{{ .db_database }}"
  data:
    - secretKey: db_host
      remoteRef:
        key: ferdium-db-secret
        property: DB_HOST
    - secretKey: db_port
      remoteRef:
        key: ferdium-db-secret
        property: DB_PORT
    - secretKey: db_user
      remoteRef:
        key: ferdium-db-secret
        property: DB_USER
    - secretKey: db_password
      remoteRef:
        key: ferdium-db-secret
        property: DB_PASSWORD
    - secretKey: db_database
      remoteRef:
        key: ferdium-db-secret
        property: DB_DATABASE
