---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ferdium
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn:
    - name: smtp-relay
      namespace: network
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      ferdium:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/ferdium/ferdium-server
              tag: 2.0.13
            env:
              TZ: America/Chicago
              NODE_ENV: production
              APP_URL: "https://ferdium.barn-walleye.ts.net"
              CONNECT_WITH_FRANZ: "false"
              DATA_DIR: /data
              DB_CONNECTION: pg
              DB_SSL: "false"
              IS_CREATION_ENABLED: "false"
              IS_REGISTRATION_ENABLED: "false"
              IS_DASHBOARD_ENABLED: "true"
              JWT_USE_PEM: "true"
              MAIL_CONNECTION: smtp
              MAIL_SENDER: ferdium@gddnet.io
              MAIL_SSL: "false"
              SMTP_HOST: smtp-relay.network.svc.cluster.local
              SMTP_PORT: "2525"
            envFrom:
              - secretRef:
                  name: ferdium-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3333
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
          - path: /app/recipes
            subPath: recipes
      tmp:
        type: emptyDir
