---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gdd-plex
components:
  - ../../components/common
resources:
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml