---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: plex
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      sonarr:
        type: statefulset
        annotations:
          secret.reloader.stakater.com/reload: &secret sonarr-secret
          
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.11.2774
            env:
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__APP__THEME: dark
              SONARR__LOG__ANALYTICSENABLED: "False"
              SONARR__LOG__DBENABLED: "False"
              SONARR__LOG__LEVEL: info
              SONARR__SERVER__PORT: &port 80
              SONARR__POSTGRES__HOST: "postgres16-rw.database.svc.cluster.local"
              SONARR__POSTGRES__PORT: "5432"
              SONARR__POSTGRES__USER: "plex_sonarr"
              SONARR__POSTGRES__MAINDB: "plex_sonarr"
              SONARR__AUTH__REQUIRED: Enabled
              SONARR__AUTH__METHOD: Forms
              SONARR__AUTH__ENABLED: True
              TZ: America/Chicago
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 300Mi
    service:
      app:
        controller: sonarr
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Plex
          gethomepage.dev/name: Sonarr
          gethomepage.dev/icon: sonarr.svg
          gethomepage.dev/widget.type: sonarr
          gethomepage.dev/widget.url: http://sonarr.plex
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_SONARR_TOKEN}}`}}"
        hosts:
          - host: &host sonarr.int.gddnet.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        type: emptyDir
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: 10.0.30.134
        path: /medianfs
        globalMounts:
          - path: /mnt/media