---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux-Kustomizations
  - ./cloudnative-pg/ks.yaml
#  - ./emqx/ks.yaml
#  - ./mariadb/ks.yaml
#  - ./dbeaver/ks.yaml
#  - ./dragonfly-operator/ks.yaml