---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
    - name: zwave2mqtt
    - name: zigbee2mqtt
  values:
    controllers:
      homeassistant:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.10.1@sha256:c2febd5870a769d2131b2a716f3ed447289984e440ff415f3e634a6233101bb8
            env:
              TZ: America/Chicago
              HASS_HTTP_TRUSTED_PROXY_1: 10.244.0.0/16
              HASS_HTTP_TRUSTED_PROXY_2: 10.0.0.0/8
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: &port 8123
    serviceMonitor:
      app:
        endpoints:
          - port: http
    route:
      app:
        hostnames: ["jarvis.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      app:
        type: persistentVolumeClaim
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 500Mi
        globalMounts:
          - path: /config
      tmpfs:
        type: emptyDir
        advancedMounts:
          homeassistant:
            app:
              - path: /config/logs
                subPath: logs
              - path: /config/tts
                subPath: tts
              - path: /tmp
                subPath: tmp