
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: observability 
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: GF_DATABASE_NAME
    remoteRef:
      key: "9beafc37-cc22-407b-9a09-b22a0095815a"
  - secretKey: GF_DATABASE_HOST
    remoteRef:
      key: "8c8d21b1-2431-452b-b85b-b22a00959482"
  - secretKey: GF_DATABASE_USER
    remoteRef:
      key: "f3e51de2-7239-4722-95b6-b22a0095ccf2"
  - secretKey: GF_DATABASE_PASSWORD
    remoteRef:
      key: "aa05d4c0-36f2-46ce-b2bb-b22a0095f665"
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    remoteRef:
      key: "074a6b48-c091-4873-b4a3-b22a00964198"
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    remoteRef:
      key: "02e76291-f9ed-469e-adae-b22a00965655"


