# =============================================================================
# !! PLAINTEXT — ENCRYPT WITH SOPS BEFORE `git add` !!
#   sops --age age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y \
#        --encrypt --encrypted-regex '^(data|stringData)$' --in-place \
#        kubernetes/apps/gdd-service/meowmeowgood/app/secret.sops.yaml
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: meowmeowgood-secret
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:neYrw6YStMDwkeLHMbRL,iv:uqbOxFc6A433fGfb1tOnGrMXKF3QcSNTbNQBlix5D2o=,tag:aaVy0rr/vEL/qmx2D9q2dA==,type:str]
    DJANGO_DEBUG: ENC[AES256_GCM,data:9KOtKlI=,iv:tOq/E1JtEBlhWsI/oBL4NSIsaFDyrXn/11+06V9nPiA=,tag:Jxt+3ZlqkMUnaNhQ7/qEzA==,type:str]
    DJANGO_ALLOWED_HOSTS: ENC[AES256_GCM,data:1j4QSM4nftjQiE1UBYjdxbgoWp53dT88FHfrs6ZGCK34zHyRVr5B9kxP,iv:4Z9dtj1Yx5NRy98PMyFI1ogziKldTjBPnYBeV6nsrmo=,tag:lb6ina1aZMaLQor11+xr5A==,type:str]
    DJANGO_CSRF_TRUSTED_ORIGINS: ENC[AES256_GCM,data:aPbDqPgK/pTJE0tSSLQXAjCM8mnDjJezOjQj/AIQ,iv:2jzmEhrXiV6bdo65ho0EwH39MKrrvAQIbqnyN4Fbs6I=,tag:qHvPGn1KxLUrtjH93qa3xQ==,type:str]
    OIDC_PROVIDER_ID: ENC[AES256_GCM,data:sFiGyQ==,iv:5AfVdMWcjbOZfF02H1DnRDYLpLUqXSRh+JCOMD4YI9M=,tag:KIaLLIBsB/FfxxVNUIPYNw==,type:str]
    OIDC_DISPLAY_NAME: ENC[AES256_GCM,data:kiLNuKvt6tkEigP3vPMxvw==,iv:JFLLDzMbumv56IXlkIYGLJMSMhPe2kz+/ZLcjgFzWyU=,tag:97cEW4+wAujUg01FT5DrIw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:7T6pY2zajntxhJjMLS6GcDpyTcVCg01PuV3yx8QTRTetefkmRuyeuQ==,iv:b2GJks3IL15Ew/+6bY1TZXa57U31M8KTsD4EtX7kyWE=,tag:Qmlt4+3HOFXDp+JrhAbv6Q==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:P3kWcQkBjMOFuIbrHi8TeqMWJMvOvVy3hp4HktAjqh/ir7A3eWQmjGMmW23P8WqzKK+uz4DHELhW4+ddBbOUOWJKjaTyFalIVWMwKQsr8fJ4llFu2efDRV5om9Cx3j6eWVmtvZFcLJx5iptzITFqoURnwr/sDXLWPR2O2wDLI9E=,iv:4DkiWsak9PfTArBq0+qMWQYedHOaemi6dt1x2W4fV+0=,tag:vcy0ysvm3oWHpUGMvEHkEQ==,type:str]
    OIDC_SERVER_URL: ENC[AES256_GCM,data:nvxq0gw8HxA90pcJdn+dPnzTVjZxL29QlyUl6fmgbJHHDairtW11kAnrpVzGlzs+QOrP4OhmGr7eOB/tBs/gG8/a9qIJvYx/hiiE4EE5Y8d1,iv:6GhFkiwLVacioRTgrfwXSkfl9v7FuOwCogVXs6CJXdQ=,tag:6kCbhHDuyPup2qyrdC5CGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSzNwbVZHMjQzbkw2RWpv
            Z1RlUkhZV0ZEcnozdGZ1ZzBaZldzYjdpSTFBCk1sMkl0VXZ5K2Z4WW9sWjdMMnhS
            YWpzR2VQV0VZbEhla3NnbWlhMUpuV2sKLS0tIFV3UEJCUWgzY21NK1NadnM2ZTFH
            Q1pLWVdzbUI3UzNLVHQxQ0ZSUEtXdzgKTvR4KT8Wp4+SE9LiCZIOisKL28rKiOZk
            5P3Czbpx56S7xLII1M6StLV8zpo/yLwZnGSsVDItP2fV4blbNoRHYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T06:23:35Z"
    mac: ENC[AES256_GCM,data:SWfTqv1UcT4KGp2gNhFE7HUhhKjljXyC/rwSD0x/y6tHh7QpfcpHkH1fv+ikXwKBRATZo0GZ0B+wGB/MTnj0Z7R6A5WLSFFV0i/nkP+/Rsb47/eCU1GQaXawz3jGpEU3ywSxkeRi0qaVkpydwJ46YbSd324TIu1hZRD68dOBXBQ=,iv:FHMGXF1syNTSYUGkZ95kQUSqISimzlkOBZKbqqAi3mU=,tag:KCr0vLPKxlcjhR1K/DedVA==,type:str]
    version: 3.13.3
