
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: security
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: "8239790e-50e0-4498-b3df-b21b007fe74a"
  - secretKey: AUTHENTIK_POSTGRES__PASSWORD
    remoteRef:
      key: "b9dd5489-bba6-4f69-8c79-b21b0063d58e"
  - secretKey: AUTHENTIK_POSTGRES__USER
    remoteRef:
      key: "d0ec47e1-16fb-4ab5-8273-b228013211b0"
  - secretKey: AUTHENTIK_POSTGRES__NAME
    remoteRef:
      key: "9920a731-e663-4c35-b18b-b22801322a0e"
  - secretKey: AUTHENTIK_POSTGRES__HOST
    remoteRef:
      key: "e39f4c0d-040a-4c96-8fcf-b228013244df"
  - secretKey: AUTHENTIK_STORAGE__MEDIA__BACKEND
    remoteRef:
      key: "ee412484-9085-49d0-bb45-b22801326b21"
  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
    remoteRef:
      key: "d8537841-5aa4-4fd9-9419-b228014fcab8"
  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
    remoteRef:
      key: "21a84b16-f572-47a7-a975-b228014fe1e0"
  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME
    remoteRef:
      key: "1cd0f480-cdb7-493f-811a-b228014ffe0e"
  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT
    remoteRef:
      key: "abd6eb60-0301-4a7c-a3e4-b22801501d15"
  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN
    remoteRef:
      key: "7f4e0d1f-fbf5-46c5-8728-b22801515dfa"

#
#        AUTHENTIK_EMAIL__HOST: "{{ .SMTP_HOST }}"
#        AUTHENTIK_EMAIL__PORT: "{{ .SMTP_PORT }}"
#        AUTHENTIK_EMAIL__USERNAME: "{{ .SMTP_USERNAME }}"
#        AUTHENTIK_EMAIL__PASSWORD: "{{ .SMTP_PASS }}"
#        AUTHENTIK_EMAIL__USE_SSL: "true"
#        AUTHENTIK_EMAIL__FROM: "Authentik <auth@${PUBLIC_DOMAIN}>"
