
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: security
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: "8239790e-50e0-4498-b3df-b21b007fe74a"
  - secretKey: AUTHENTIK_POSTGRES__PASSWORD
    remoteRef:
      key: "b9dd5489-bba6-4f69-8c79-b21b0063d58e"
  - secretKey: AUTHENTIK_POSTGRES__USER
    remoteRef:
      key: ""
  - secretKey: AUTHENTIK_POSTGRES__NAME
    remoteRef:
      key: ""
  - secretKey: AUTHENTIK_POSTGRES__HOST
    remoteRef:
      key: ""
  - secretKey: AUTHENTIK_STORAGE__MEDIA__BACKEND
    remoteRef:
      key: ""
#  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
#    remoteRef:
#      key: ""
#  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
#    remoteRef:
#      key: ""
#  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME
#    remoteRef:
#      key: ""
#  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__REGION
#    remoteRef:
#      key: ""
#  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT
#    remoteRef:
#      key: ""
#  - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN
#    remoteRef:
#      key: ""


#
#        AUTHENTIK_EMAIL__HOST: "{{ .SMTP_HOST }}"
#        AUTHENTIK_EMAIL__PORT: "{{ .SMTP_PORT }}"
#        AUTHENTIK_EMAIL__USERNAME: "{{ .SMTP_USERNAME }}"
#        AUTHENTIK_EMAIL__PASSWORD: "{{ .SMTP_PASS }}"
#        AUTHENTIK_EMAIL__USE_SSL: "true"
#        AUTHENTIK_EMAIL__FROM: "Authentik <auth@${PUBLIC_DOMAIN}>"
