---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.12.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2024.12.2
      fullnameOverride: authentik
      envFrom:
        - secretRef:
            name: authentik-secret

    authentik:
      redis:
        host: dragonfly.database.svc.cluster.local
        db: 1
      log_level: info
      avatars: "initials"
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
    server:
      envFrom:
        - secretRef:
            name: authentik-secret
      replicas: 2
      pdb:
        enabled: true
        minAvailable: 1
        maxUnavailable: 1
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.gddnet.io
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Security
          gethomepage.dev/name: Authentik
          gethomepage.dev/icon: authentik.png
          gethomepage.dev/pod-selector: app.kubernetes.io/name=authentik

        hosts:
          - "sso.gddnet.io"
        paths:
          - /

      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 2Gi
    worker:
      envFrom:
        - secretRef:
            name: authentik-secret
      replicas: 2
      pdb:
        enabled: true
        minAvailable: 1
        maxUnavailable: 1
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          memory: 1Gi
    prometheus:
      rules:
        enabled: true

    postgresql:
      enabled: false
    redis:
      enabled: false