---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-config
  namespace: gdd-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: romm-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: |
          emulatorjs:
            netplay:
              enabled: true
              ice_servers:
                - urls: "stun:stun.relay.metered.ca:80"
                - urls: "turn:standard.relay.metered.ca:80"
                  username: "{{ .turn_username }}"
                  credential: "{{ .turn_credential }}"
                - urls: "turn:standard.relay.metered.ca:80?transport=tcp"
                  username: "{{ .turn_username }}"
                  credential: "{{ .turn_credential }}"
                - urls: "turn:standard.relay.metered.ca:443"
                  username: "{{ .turn_username }}"
                  credential: "{{ .turn_credential }}"
                - urls: "turns:standard.relay.metered.ca:443?transport=tcp"
                  username: "{{ .turn_username }}"
                  credential: "{{ .turn_credential }}"
  data:
    - secretKey: turn_username
      remoteRef:
        key: romm-turn-secret
        property: username
    - secretKey: turn_credential
      remoteRef:
        key: romm-turn-secret
        property: credential
