---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: romm-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_PASSWD: "{{ .db_password }}"
        ROMM_AUTH_SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: romm-db-secret
        property: password
    - secretKey: secret_key
      remoteRef:
        key: romm-app-secret
        property: SECRET_KEY
