---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: comfyui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      comfyui:
        strategy: Recreate
        containers:
          app:
            image:
              repository: yanwk/comfyui-boot
              tag: xpu-20260420
            env:
              TZ: America/Chicago
              CLI_ARGS: ""
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            securityContext:
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 100m
                memory: 4Gi
                gpu.intel.com/xe: 1
              limits:
                memory: 24Gi
                gpu.intel.com/xe: 1
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
      hostIPC: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: In
                    values: ["true"]
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: ["gddnet-w9"]
    service:
      app:
        ports:
          http:
            port: &port 8188
#    route:
#      app:
#        hostnames: ["comfyui.${SECRET_DOMAIN}"]
#        annotations:
#          gethomepage.dev/enabled: "true"
#          gethomepage.dev/group: AI
#          gethomepage.dev/name: ComfyUI
#          gethomepage.dev/icon: comfyui.svg
#          gethomepage.dev/description: "AI image generation workflow"
#        parentRefs:
#          - name: external
#            namespace: kube-system
#            sectionName: https
#        rules:
#          - backendRefs:
#              - identifier: app
#                port: *port
    persistence:
      models:
        type: persistentVolumeClaim
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 500Gi
        globalMounts:
          - path: /root/ComfyUI/models
      output:
        type: persistentVolumeClaim
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 50Gi
        globalMounts:
          - path: /root/ComfyUI/output
      tmp:
        type: emptyDir
