---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: gdd-service
data:
  config.yaml: |
    log:
      level: info
    runner:
      file: /data/.runner
      capacity: 3
      timeout: 3h
    cache:
      enabled: true
      dir: /data/cache
    container:
      docker_host: "tcp://localhost:2375"
      privileged: true
      workdir_parent: /data/workdir
