---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        uuid: "{{ .uuid }}"
        token: "{{ .token }}"
  data:
    - secretKey: uuid
      remoteRef:
        key: "05f6a6c5-fa12-452a-af7b-b45e00469a21"
        property: uuid
    - secretKey: token
      remoteRef:
        key: "a4d58fb5-bcc2-457d-b155-b45e00424674"
        property: token
