---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner
  namespace: gdd-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
