apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:WNHMqVL6g1axtOvKNeY0dvrEpBIQnb/XqUqaLmVoZtXfNTCk21Tl+A==,iv:XjiipOvb4WkPsRaMcAzgQrttePBx4eKL8gII8bChrIE=,tag:JGMR/iUt8l9fwWpS9chcAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10jmn4ckmtds58xyf530gcs59khplgcr6z3whme7jpyrg4rxvpads5ky24w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y084eStsUjlnNjJYUURX
            eTR4RUJSbHJEZ3NnemgyTC80NDB6Vi9VWDFnCjIxOFJjUnphQzZiS0FLSmdaR1JO
            SDF1aFVjS2Jib0lWRytpcEY1amkreG8KLS0tIEhPcVZqaFpVelUvUUZ1SFg4RnZK
            VzkyMjZ3Vm1CN3hhQWl3Ui9tWmlhKzgKZa4gdtONzaPHFBwUOhZeGJS66xPPJCFy
            601H26Ro2AelwkYsXxycmvDw9RfzwQLdkTC+uP0kc2QEZ8AgwrpQpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T21:12:37Z"
    mac: ENC[AES256_GCM,data:Vcd6cO09L6M1VxBSBSxl9z1/rQ8b0NWhIITmMn5cOjGuUTtQxnYujz+g/bZdhF+YQHl6uHZRN+jy6vQ/RVq9AOQ6OKAEhTe/UTzwQMm13bHJCE/uAeIDEjVFfp75ghSe8GVadkkMLtTe1Le1afbJo4K94umBlB7emes/tOmxZdk=,iv:SuStcJvF22yByBupRdPQww5O8z6KrULqItEpXkqLVfM=,tag:3M5td7erQEYQqAbS8Bu0Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
