---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stash
  annotations:
    tailscale.com/proxy-group: ts-ingress
spec:
  ingressClassName: tailscale
  rules:
    - host: stash.barn-walleye.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stash
                port:
                  number: 9999
  tls:
    - hosts:
        - stash.barn-walleye.ts.net
