apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doubletake
  namespace: jarvis
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: DT_MQTT_PASSWORD
    remoteRef:
      key: "e65ecd87-6469-4539-9ae3-b2190143a424"
  - secretKey: DT_MQTT_USERNAME
    remoteRef:
      key: "649b3aca-eb9b-4a69-b25b-b219014387b7"
