---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellyfin
  namespace: flux-system
spec:
  targetNamespace: &ns plex
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  components:
#    - ../../../../templates/gatus/guarded
    - ../../../../templates/volsync
#  dependsOn:
##    - name: rook-ceph-cluster
#      namespace: rook-ceph
  path: ./kubernetes/apps/plex/jellyfin/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      NS: *ns
      VOLSYNC_CAPACITY: 30Gi
