---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: service-forgejo
  namespace: database
spec:
  cluster:
    name: postgres
  name: service_forgejo
  owner: service_forgejo_user
  ensure: present
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: forgejo-db-password
  namespace: database
spec:
  length: 48
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-secret
  namespace: database
spec:
  refreshInterval: 12h
  target:
    name: forgejo-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: service_forgejo_user
        password: "{{ .password | toString }}"
        POSTGRES_URL: "postgresql://service_forgejo_user:{{ .password | toString }}@postgres-rw.database.svc.cluster.local:5432/service_forgejo"
        POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "service_forgejo"
        POSTGRES_USER: "service_forgejo_user"
        POSTGRES_PASSWORD: "{{ .password | toString }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: forgejo-db-password
