
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monica-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: APP_KEY
    remoteRef:
      key: "4985977c-0bab-4953-8fde-b2270064422f"
  - secretKey: DB_USERNAME
    remoteRef:
      key: "6bfcec96-c340-4fa4-a94a-b22700645fd1"
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "67c975a2-12da-4784-98d3-b2270064775e"
  - secretKey: MAIL_HOST
    remoteRef:
      key: "67d157c8-7dc5-4f03-b8e2-b227006495da"
  - secretKey: MAIL_USERNAME
    remoteRef:
      key: "7af74449-9b34-4392-8a25-b2270064a912"
  - secretKey: MAIL_PASSWORD
    remoteRef:
      key: "6908641d-687b-4189-aa5f-b2270064c305"
  - secretKey: MAIL_FROM_ADDRESS
    remoteRef:
      key: "d4cac6c8-b20d-44e1-9610-b2270064d8e1"



