---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monica
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      monica:
        annotations:
          secret.reloader.stakater.com/reload: &secret monica-secret
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: monica
              tag: 4.1.2
            env:
              TZ: America/Chicago
              APP_ENV: local
              APP_DEBUG: false
              APP_URL: http://monica.gddnet.io
              APP_TRUSTED_PROXIES: "*"
              MFA_ENABLED: true
              DAV_ENABLED: true
              DB_USE_UTF8MB4: true
              DB_HOST: "mariadb.database.svc.cluster.local"
              DB_DATABASE: "service_monica"
              MAIL_MAILER: "smtp"
              MAIL_PORT: "465"
              MAIL_ENCRYPTION: "tls"
              MAIL_FROM_ADDRESS: "noreply@securitylab.io"
              MAIL_FROM_NAME: "Monica"
              # LOG_LEVEL: debug
            envFrom:
              - secretRef:
                  name: monica-secret

    service:
      app:
        controller: monica
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Service
          gethomepage.dev/name: Monica
          gethomepage.dev/icon: monica.svg
          gatus.io/path: *path
        hosts:
          - host: monica.int.gddnet.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    serviceAccount:
      create: true
