---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: stasharr-db-password
  namespace: gdd-service
spec:
  length: 48
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stasharr-secret
  namespace: gdd-service
spec:
  refreshInterval: "0"
  target:
    name: stasharr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: stasharr
        POSTGRES_USER: stasharr
        POSTGRES_PASSWORD: "{{ .password | toString }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: stasharr-db-password
