---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stasharr
  annotations:
    tailscale.com/proxy-group: ts-ingress
spec:
  ingressClassName: tailscale
  rules:
    - host: stasharr.barn-walleye.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stasharr
                port:
                  number: 3000
  tls:
    - hosts:
        - stasharr.barn-walleye.ts.net
