
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellystat-secret
  namespace: gdd-plex
spec:
  refreshInterval: 12h
  target:
    name: jellystat-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_PASSWORD: "{{ .password }}"
        JWT_SECRET: "{{ .jwt_secret }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: kubernetes-secret-store
          kind: ClusterSecretStore
      remoteRef:
        key: jellystat-db-secret
        property: password
    - secretKey: jwt_secret
      sourceRef:
        storeRef:
          name: bitwarden
          kind: ClusterSecretStore
      remoteRef:
        key: "ea932799-89d5-466f-a0a3-b39500732304"
