---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tandoor
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      tandoor:
        labels:
          postgres: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 2.0.2@sha256:79f337a334207d0fe49732197ee721f363aeaac8a600b75560e23c72ba5a8c25
            env:
              TZ: ${TIMEZONE}
              ALLOWED_HOSTS: "*"
              AI_MODEL_NAME: openai/gpt-4o
              COMMENT_PREF_DEFAULT: 1
              DB_ENGINE: django.db.backends.postgresql_psycopg2
              DEBUG: 0
              DEFAULT_FROM_EMAIL: recipes@${SECRET_DOMAIN}
              EMAIL_HOST: smtp-relay.networking.svc.cluster.local
              EMAIL_PORT: 2525
              ENABLE_SIGNUP: 0
              FRACTION_PREF_DEFAULT: 0
              GUNICORN_MEDIA: 0
              SHOPPING_MIN_AUTOSYNC_INTERVAL: 5
              SOCIAL_PROVIDERS: allauth.socialaccount.providers.openid_connect
              TANDOOR_PORT: &port 8000
            envFrom:
              - secretRef:
                  name: tandoor-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1024Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8000
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.gddnet.io
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Tandoor
          gethomepage.dev/description: Managing recipes, planned meals, shopping lists.
          gethomepage.dev/group: Service
          gethomepage.dev/icon: tandoor.png
        hosts:
          - host: &host "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: tandoor-config
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/mediafiles
                subPath: mediafiles
              - path: /opt/recipes/staticfiles
                subPath: staticfiles
      tmpfs:
        type: emptyDir
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/cookbook/static/django_js_reverse
                subPath: django_js_reverse
              - path: /var/lib/nginx/logs
                subPath: nginx_logs
              - path: /var/lib/nginx/tmp
                subPath: nginx_tmp
              - path: /tmp
                subPath: tmp
