
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: windmill-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: WINDMILL_DB_PASSWORD
    remoteRef:
      key: "7b7124e9-b86f-4f41-a3a2-b26d017645a3"
  target:
    template:
      engineVersion: v2
      data:
        WINDMILL_POSTGRES_URL: 'postgres://service_windmill:{{ index . "WINDMILL_DB_PASSWORD" }}@postgres16-rw.database.svc.cluster.local/service_windmill'
