---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app windmill
spec:
  interval: 30m
  chart:
    spec:
      chart: windmill
      version: 2.0.369
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    windmill:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
      baseDomain: &host "apps.gddnet.io"
      baseProtocol: https
      appReplicas: 1
      lspReplicas: 1
      multiplayerReplicas: 1
      workerGroups:
        - name: default
          replicas: 2
          resources:
            requests:
              memory: 1028Mi
              cpu: 500m
            limits:
              memory: 2048Mi
        - name: native
          replicas: 1
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: external.gddnet.io
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Apps
        gethomepage.dev/description: Developer platform to turn scripts into workflows and UIs
        gethomepage.dev/group: Services
        gethomepage.dev/icon: webhook.png
        gethomepage.dev/href: https://apps.gddnet.io
        gethomepage.dev/pod-selector: >-
          app in (
            windmill-app,
            windmill-workers,
            windmill-lsp
          )
      className: external
    postgresql:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: windmill-secret
      valuesKey: WINDMILL_POSTGRES_URL
      targetPath: windmill.databaseUrl