---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      zigbee2mqtt:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.40.2@sha256:40dca7e6ee816c84d6220daeb92cf20a52cf35446ec1d3ef0c2965a87cd397cc
            env:
              TZ: America/New_York
              ZIGBEE2MQTT_DATA: /config
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6af289ca5c3bec1192e4a4957a0af07f-if00-port0
              # DEBUG: "zigbee-herdsman*"
#            envFrom:
#              - secretRef:
#                  name: zigbee2mqtt-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 512Mi
        pod:
          nodeSelector:
            aeotec.feature.node.kubernetes.io/zwave: "true"
    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            port: 8080
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.gddnet.io
        className: internal
        hosts:
          - host: zigbee.m.gddnet.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: zigbee
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6af289ca5c3bec1192e4a4957a0af07f-if00-port0
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6af289ca5c3bec1192e4a4957a0af07f-if00-port0