
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snipeit-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: APP_KEY
    remoteRef:
      key: "fbb8c97b-db83-4380-89d9-b25701411cf9"
  - secretKey: DB_USERNAME
    remoteRef:
      key: "c1fd323a-37d2-48b4-a79d-b25701409043"
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "a20a330b-d08a-49cf-9c1d-b2570140cf8b"
  - secretKey: MYSQL_ROOT_PASSWORD
    remoteRef:
      key: "a20a330b-d08a-49cf-9c1d-b2570140cf8b"
  - secretKey: MAIL_USERNAME
    remoteRef:
      key: "13bcf769-75cc-4bfa-a7be-b2570140e777"
  - secretKey: MAIL_PASSWORD
    remoteRef:
      key: "d2d19439-49f6-4d70-b4e3-b257014102c2"

