---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snipeit
  namespace: service
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      snipeit:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: snipe/snipe-it
              tag: v8.1.16
            env:
              TZ: America/Chicago
              APP_VERSION: 6.4.1
              APP_PORT: 80   
              APP_ENV: production
              APP_DEBUG: false
              APP_URL: https://stuff.gddnet.io
              APP_TIMEZONE: 'America/Chicago'
              APP_LOCALE: en-US
              MAX_RESULTS: 500
              SECURE_COOKIES: true
              APP_FORCE_TLS: true
              DB_HOST: mariadb.database.svc.cluster.local
              DB_PORT: '3306'
              DB_DATABASE: snipeit
              DB_CHARSET: utf8mb4
              DB_COLLATION: utf8mb4_unicode_ci
              MAIL_MAILER: smtp
              MAIL_HOST: smtp.mailgun.org
              MAIL_PORT: 465
              MAIL_TLS_VERIFY_PEER: true
              MAIL_FROM_ADDR: no-reply@mail.gddnet.io
              MAIL_FROM_NAME: 'Snipe-IT'
              MAIL_REPLYTO_ADDR: no-reply@mail.gddnet.io
              MAIL_REPLYTO_NAME: 'Snipe-IT'
              MAIL_AUTO_EMBED_METHOD: 'attachment'
              APP_TRUSTED_PROXIES: 10.0.0.0/8,172.16.0.0/12
            envFrom:
              - secretRef:
                  name: snipeit-secret

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512M

    service:
      app:
        controller: snipeit
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.gddnet.io
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Stuff Inventory
          gethomepage.dev/icon: mdi-treasure-chest-outline
          gethomepage.dev/group: Service

        hosts:
          - host: "stuff.gddnet.io"
            paths:
              - path: "/"
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - stuff.gddnet.io

    persistence:
      data:
        existingClaim: snipeit-data
        advancedMounts:
          snipeit:
            app:
              - path: /var/lib/snipeit