apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: database
  labels:
    homelab/usage: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: database
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: mariadb
      name: mariadb
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb
---
# Source: home-assistant/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: database
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/instance: mariadb
      annotations:
    spec:
      securityContext:
        {}
      containers:
        - name: mariadb
          securityContext:
            {}
          image: "mysql:8.0.26"
          imagePullPolicy: IfNotPresent
#          command: ["mysqld_safe"]
#          args: ["--skip-grant-tables", "--skip-networking"]
          ports:
            - name: mariadb
              containerPort: 3306
              protocol: TCP

          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: mariadb
---
apiVersion: v1
kind: Secret
metadata:
   name: restic-config
type: Opaque
stringData:
   RESTIC_REPOSITORY: s3:s3.us-west-000.backblazeb2.com/talos-gdd/source/mariadb
   RESTIC_PASSWORD: Quotation-Elitism-Radial-Overhand
   AWS_ACCESS_KEY_ID: 0002a8de8b29fa00000000003
   AWS_SECRET_ACCESS_KEY: K000h5udEQeLOcrc++AafnlDVUICkU8
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: mariadb
   namespace: database
spec:
   sourcePVC: mariadb
   trigger:
      schedule: "*/30 * * * *"
   restic:
     pruneIntervalDays: 15
     repository: restic-config
     retain:
       hourly: 1
       daily: 1
       weekly: 1
       monthly: 1
       yearly: 1
     copyMethod: Clone
