---
apiVersion: v1
kind: Secret
metadata:
   name: restic-config
type: Opaque
stringData:
   RESTIC_REPOSITORY: s3:s3.us-west-000.backblazeb2.com/talos-gdd/source/plexserver
   RESTIC_PASSWORD: Quotation-Elitism-Radial-Overhand
   AWS_ACCESS_KEY_ID: 0002a8de8b29fa00000000003
   AWS_SECRET_ACCESS_KEY: K000h5udEQeLOcrc++AafnlDVUICkU8
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: plex
   namespace: plex
spec:
   sourcePVC: plex
   trigger:
      schedule: "*/30 * * * *"
   restic:
     pruneIntervalDays: 15
     repository: restic-config
     retain:
       hourly: 1
       daily: 1
       weekly: 1
       monthly: 1
       yearly: 1
     copyMethod: Clone
