apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: database
  labels:
    homelab/usage: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 20Gi
