apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: database
  labels:
    homelab/usage: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 20Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: mariadb
   namespace: database
spec:
   sourcePVC: mariadb
   trigger:
      schedule: "*/30 * * * *"
   restic:
     pruneIntervalDays: 15
     repository: restic-mariadb
     retain:
       hourly: 1
       daily: 1
       weekly: 1
       monthly: 1
       yearly: 1
     copyMethod: Clone