---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inventree-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: inventree-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INVENTREE_DB_PASSWORD: "{{ .db_password }}"
        INVENTREE_SECRET_KEY: "{{ .secret_key }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: inventree-db-secret
        property: password
    - secretKey: secret_key
      remoteRef:
        key: inventree-app-secret
        property: SECRET_KEY
