---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: junimoserver-secret
  namespace: gdd-game
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: STEAM_USERNAME
      remoteRef:
        key: "4cbf0b30-acb3-4b16-9270-b427012f60c0"
    - secretKey: STEAM_PASSWORD
      remoteRef:
        key: "1410fe17-b3e5-40a6-9c64-b427012f7d02"
    - secretKey: VNC_PASSWORD
      remoteRef:
        key: "a2f9ec88-3d65-4b02-b6a0-b427012f9cf8"
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: "a4c34c24-29cc-4f0a-a836-b427012fc602"

