
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manyfold-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: SECRET_KEY_BASE
    remoteRef:
      key: "349bd92f-66c4-4be8-a5b9-b22f0083333e"
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: "9e3a5b0b-6218-49cf-b1f3-b22f00834421"
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: "7dc5776e-d116-43fe-98c3-b22f0083565a"
  - secretKey: OIDC_ISSUER
    remoteRef:
      key: "6a6f104d-bbe6-49f0-86b0-b22f00836ba2"





