---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: service-manyfold
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      manyfold:
        annotations:
          secret.reloader.stakater.com/reload: manyfold-secret

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"

        initContainers:
          chown-tmpdirs:
            image:
              repository: docker.io/library/alpine
              tag: "3.21"
            command:
              - /bin/sh
              - -c
            args:
              - |
                chmod o-rwx /app/tmp /app/log /tmp
            securityContext:
              runAsUser: 0

        containers:
          main:
            image:
              repository: ghcr.io/bjw-s-labs/manyfold
              tag: 0.99.1@sha256:8d187ecac91d04a86e29757d5844a9a0e0362aceb6b35d67ca11971df5ae2fd2
            envFrom:
              - secretRef:
                  name: manyfold-secret
            env:
              DATABASE_URL: sqlite3:/data/database/manyfold.sqlite3
              MULTIUSER: enabled
              PORT: &httpPort 3214
              REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379
              REGISTRATION: enabled 
              OIDC_NAME: SSO
              PUBLIC_HOSTNAME: https://manyfold.int.gddnet.io
              PUBLIC_PORT: 443
              FORCE_OIDC: false
              SECRET_KEY_BASE:
                valueFrom:
                  secretKeyRef:
                    name: manyfold-secret
                    key: SECRET_KEY_BASE
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL


    service:
      app:
        controller: manyfold
        ports:
          http:
            port: *httpPort


    ingress:
      app:
        className: "internal"
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.gddnet.io
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Service
          gethomepage.dev/name: ManyFold
          gethomepage.dev/icon: manyfold.png
        hosts:
          - host: manyfold.int.gddnet.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: manyfold-data
        advancedMounts:
          manyfold:
            main:
              - path: /data/database
                subPath: database
              - path: /data/libraries/main
                subPath: libraries/main
      tmpfs:
        enabled: true
        type: emptyDir
        advancedMounts:
          manyfold:
            main: &tmpdirs
              - path: /tmp
                subPath: host-tmp
              - path: /app/tmp
                subPath: app-tmp
              - path: /app/log
                subPath: app-log
            chown-tmpdirs: *tmpdirs