
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obskurnee-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: DB_ENGINE
    remoteRef:
      key: "26afebbd-79fc-485a-a9aa-b2280172a4ea"
  - secretKey: SECRET_KEY
    remoteRef:
      key: "285e1a94-9fcf-4a2f-a5ba-b2280172ca56"
  - secretKey: Mailgun__ApiKey
    remoteRef:
      key: "d70544bd-0513-44f7-8959-b24e0002dc0e"
