---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app obskurnee
  namespace: &ns service
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      obskurnee:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: zblesk/obskurnee
              tag: 1.2.0
            envFrom: &envFrom
              - secretRef:
                  name: obskurnee-secret
            env:
              DEBUG: "0"
              SiteName: Book club!
              BaseUrl: https://bookclub.gddnet.io
              DefaultCulture: en
              SymmetricSecurityKey: 87965trfvbh86somebigrandomsecuritykeyhere
              MailerType: mailgun
              Mailgun__EndpointUri: https://api.mailgun.net/v3/
              Mailgun__SenderEmail: Bookclub <bookclub@gddnet.io>
              Mailgun__SenderDomainName: gddnet.io
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.gddnet.io
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Book Club
          gethomepage.dev/description: Managing recipes, planned meals, shopping lists.
          gethomepage.dev/group: Service
          gethomepage.dev/icon: tandoor.png
          
        hosts:
          - host: &host "bookclub.gddnet.io"
            paths:
              - path: /
                service:
                  identifier: app


    persistence:
      config:
        existingClaim: obskurnee-config
        advancedMounts:
          obskurnee:
            app:
              - path: /obskurnee/data
