apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obskurnee-config
  namespace: service
  labels:
    homelab/usage: service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
---