---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music
  annotations:
    tailscale.com/proxy-group: ts-ingress
spec:
  ingressClassName: tailscale
  rules:
    - host: music.barn-walleye.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: music-app
                port:
                  number: 8095
  tls:
    - hosts:
        - music.barn-walleye.ts.net
