---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      headscale:
        type: statefulset
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/juanfont/headscale
              tag: v0.28.0
            command: [headscale, serve]
            envFrom:
              - secretRef:
                  name: headscale-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /health
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 12m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - headscale.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
    persistence:
      config:
        type: configMap
        name: headscale-config
        globalMounts:
          - path: /etc/headscale/config.yaml
            subPath: config.yaml
            readOnly: true
      data:
        existingClaim: headscale
        globalMounts:
          - path: /var/lib/headscale
      tmp:
        type: emptyDir
        globalMounts:
          - path: /var/run/headscale
