---
# Encrypt this file before committing: sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: headscale-secret
stringData:
  # Add headscale secret env vars here, e.g. for OIDC:
  # HEADSCALE_OIDC_CLIENT_ID: changeme
  # HEADSCALE_OIDC_CLIENT_SECRET: changeme
