---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ogamex-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: "TODO-bitwarden-item-uuid-ogamex"
        property: APP_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "TODO-bitwarden-item-uuid-ogamex"
        property: DB_PASSWORD
    - secretKey: REVERB_APP_ID
      remoteRef:
        key: "TODO-bitwarden-item-uuid-ogamex"
        property: REVERB_APP_ID
    - secretKey: REVERB_APP_KEY
      remoteRef:
        key: "TODO-bitwarden-item-uuid-ogamex"
        property: REVERB_APP_KEY
    - secretKey: REVERB_APP_SECRET
      remoteRef:
        key: "TODO-bitwarden-item-uuid-ogamex"
        property: REVERB_APP_SECRET
