# =============================================================================
# !! PLAINTEXT — ENCRYPT WITH SOPS BEFORE `git add` !!
#   sops --age age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y \
#        --encrypt --encrypted-regex '^(data|stringData)$' --in-place \
#        kubernetes/apps/gdd-game/ogamex/app/secret.sops.yaml
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: ogamex-secret
stringData:
    APP_KEY: ENC[AES256_GCM,data:OHLe1m3JuOJ59ABpYgARrKDQcNnZYx6IFF4bxzuMyhYGCpIFMk43w9ypnJ5LtTEL36zK,iv:dE/SHvv/cODD7mZGfQy/dcd7Wo1RErB/nlgTLYtRKsY=,tag:pCM5dRc0Jf8lEoSunsgiXQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:rtmxyQJrB0F8GuwBrueweilS1c46s3f3JRe+SQ0gUOJ9pvRJAwCOH2FjhgSP8n/k,iv:maP0FEDk069BNuqmRRp0xajphspbR+triCBFaEaZ7h0=,tag:1oL75fahF1uyp9QGm363Xg==,type:str]
    REVERB_APP_ID: ENC[AES256_GCM,data:FDa7vTmaloMY8kM2siEBcA==,iv:YO2UTodq0nHCBcHg8Z5HMDaVKtDNYYZl2ijTQNPP+SU=,tag:ynHTGJ5uEooFNIdIVH9n1w==,type:str]
    REVERB_APP_KEY: ENC[AES256_GCM,data:MzzkE9Fa0PgGUTcItQmvR4csXgJG/y1+QbMWWCGeG08=,iv:NOs4KJLJjCyIDBKwkz6TeTm1FN/RSDnvZQo5AY1Zga8=,tag:uoZ55PmuEBC+36/+Fbc+Ug==,type:str]
    REVERB_APP_SECRET: ENC[AES256_GCM,data:jcXY7tf4FjndNu2o3GgvMAvD8FWVR906M6CcJjBC1gH735b0ZA/Ivqp6W6cEmRM3,iv:RQ0Jx+CAD1FUGLS0oi4jziYX91w1V+37TevEZADMxpA=,tag:x/KJXxs5UoC8GjfRqeRceQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT1lEUDhvN1JSUEFHckZV
            aENQR3J2SEFtK25uZlRqZmV6NTYvakhiWDBRCkY4R0Z4OFMvaDU1QW5pbXVsRnVl
            WkZLRkZDNmNHSHlMYWhWOW9QUFMzZTQKLS0tIDVlSnJ4emcwOXpaYUxITTg4eHFu
            V0FuaGtvcEM2bUNIOGpHUUlleEMzYjQKY0HZpi/c8rbnrb73Q40HUFVqHOUq0OBL
            ygI6jAc0pam6KiG+vdxq0sXiFkR4G7NPBYZIWc1u4U8Nudi0vjpWeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T18:26:33Z"
    mac: ENC[AES256_GCM,data:uvrhLh3LsEZO/SBUmJ1bwArpD80B3RD5GA9L8YIoDVkQI4Sm4cYq6x4BOdxj/+2HtqodgYt4RYelVbxY5Pg/SXT24ynURp6MglIwxEkjAlVOGW/dTq9L834EfQeWivqhwl28mtWK6mMLTOF6CZekxRMd+WlMsf98knEhbKdGVsA=,iv:wpd1JYL/PEwpJ1W6R2NE3QEu/rRj3p2BU1r/cma+N40=,tag:3KCBrhisJ+4kfQHJvr7DUg==,type:str]
    version: 3.13.3
