---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex-overseerr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/plex/overseerr/app
  targetNamespace: plex
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname overseerr
  prune: true
  wait: false
  interval: 10m
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "568"
      APP_GID: "2000"
