---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app evcc
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      evcc:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/evcc/evcc
              tag: 0.314.2
            env:
              TZ: America/Chicago
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 7070
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        annotations:
          pangolin-operator/site-ref: homeops
          pangolin-operator/name: evcc
          pangolin-operator/full-domain: evcc.app.gddnet.io
          pangolin-operator/port: http
          pangolin-operator/auth-sso: "true"
          pangolin-operator/auth-sso-roles: Admin
        ports:
          http:
            port: *port
      ocpp:
        controller: evcc
        type: LoadBalancer
        ports:
          ocpp:
            port: 8887
            protocol: TCP
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /root/.evcc
      tmp:
        type: emptyDir
