---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-forge-world
spec:
#  dependsOn:
#    - name: external-secret-minecraft-proxy-forwarding
#    - name: external-secret-minecraft-rcon
#    - name: external-secret-minecraft-curseforge-api-key
#    - name: external-secret-minecraft-bluemap-postgres
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: java17@sha256:64c59c1104da95f2dd1bcff151de295e35176fa0133aef7f1a57692784acdb90
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  exec: &mc-health { command: ["mc-health"] }
                  failureThreshold: 20
              readiness: *probes
              startup:
                <<: *probes
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 1
                  failureThreshold: 300
                  exec: *mc-health
            envFrom:
              - secretRef:
                  name: minecraft-rcon
              - secretRef:
                  name: curseforge-api-key
              - configMapRef:
                  name: minecraft-forge-world-env
            env:
              # https://docker-minecraft-server.readthedocs.io/en/latest/variables
              TZ: America/Chicago
              TYPE: "FORGE"
              # TODO renovate
              VERSION: "1.20.1"
              MEMORY: "6024M"
              REPLACE_ENV_DURING_SYNC: "true"
              CFG_PROXY_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: minecraft-proxy-forwarding
                    key: forwarding.secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            ports:
              - name: java
                containerPort: 25565
              - name: rcon
                containerPort: 25575
              - name: metrics
                containerPort: 9100
              - name: voice
                containerPort: 24454

            resources:
              requests:
                cpu: 500m
                memory: 8Gi

    service:
      minecraft:
        controller: minecraft
        type: LoadBalancer
        ports:
          java:
            port: 25565
            protocol: TCP
          metrics:
            port: 9100
            protocol: TCP
      voice:
        controller: minecraft
        type: LoadBalancer
        ports:
          voice:
            port: 24454
            protocol: UDP
      rcon:
        controller: minecraft
        type: ClusterIP
        ports:
          rcon:
            port: 25575
            protocol: TCP

    serviceMonitor:
      metrics:
        enabled: true
        serviceName: minecraft-forge-world-minecraft
        endpoints:
          - port: metrics
            scheme: http
            path: /
            interval: 1m

    persistence:
      data:
        existingClaim: minecraft-forge-world-data
        advancedMounts:
          minecraft:
            app:
              - path: /data

