---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./kube-prometheus-stack/ks.yaml
  - ./vector/ks.yaml
  - ./loki/ks.yaml
#  - ./grafana/ks.yaml
  - ./kromgo/ks.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
        name: not-used
    target:
      kind: Namespace