
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: habittrove-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: AUTH_SECRET
    remoteRef:
      key: "e354042d-7801-42d0-955e-b29d012d7afe"
