
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: "bd888fe1-0db4-4c08-af8c-b2280172eee6"
  - secretKey: POSTGRES_PORT
    remoteRef:
      key: "9fa7f3bb-7054-41d4-ad23-b2280172ff82"
  - secretKey: POSTGRES_USER
    remoteRef:
      key: "3b461b35-7c8b-4eff-a9cc-b22c014b5214"
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: "b8728640-e567-4e37-9b55-b22c014b70d4"
  - secretKey: NEXTCLOUD_ADMIN_USER
    remoteRef:
      key: "d4cb252b-a137-4267-87d7-b22c014bba1d"
  - secretKey: NEXTCLOUD_ADMIN_PASSWORD
    remoteRef:
      key: "64c7b793-7a2d-4f5a-b6f2-b22c014bcf77"
  - secretKey: NEXTCLOUD_USERNAME
    remoteRef:
      key: "d4cb252b-a137-4267-87d7-b22c014bba1d"
  - secretKey: NEXTCLOUD_PASSWORD
    remoteRef:
      key: "64c7b793-7a2d-4f5a-b6f2-b22c014bcf77"
  - secretKey: SMTP_USERNAME
    remoteRef:
      key: "9fa7f3bb-7054-41d4-ad23-b2280172ff82"
  - secretKey: SMTP_PASSWORD
    remoteRef:
      key: "9fa7f3bb-7054-41d4-ad23-b2280172ff82"
  - secretKey: SMTP_HOST
    remoteRef:
      key: "9fa7f3bb-7054-41d4-ad23-b2280172ff82"