apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:JJegTv76ZWzp,iv:RwcbtjEfKfL+y5W/GzrZcWF3DVlPEQGJCDq1806PW3Q=,tag:PgpLPFEIlC9x7timEjPnKQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:BmIKltlt+knA/trwKA==,iv:F7kKxfR/X93FFtBMKK/K67nEuhWBHrJY2LvX6uHVZBw=,tag:PCRYeVZEeVoi0ShiRkl3zQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VV3FPbO9v1UdTJJxaOdy8dWKSuJBKDWiryeXkJ+AFsMDgFvJ,iv:nGs154I+6tl+8vLIbsgFgB0y6shirwzyVl+EKgUqCF0=,tag:jXqfEv5ekDLcHMNUPuAvFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10jmn4ckmtds58xyf530gcs59khplgcr6z3whme7jpyrg4rxvpads5ky24w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRkh3MGFDeTJnNDlKQm9u
            V012N1Q2SFlrUDduNmNPNlYraEsxUU53eDFJCnFtNGtZcTNvOFJqYWllNi9vYmxu
            RjQrUnRtbzVVaFRTbndDMXovSDZpMEUKLS0tIC9HcHRHM0lxakRuQnlPRXZGNVB4
            aDQ4VW9ack0rTXQ4R2c2WXNab3duMXcKDThMJRYMqy+atU+gibtuL3YFT7E/3kO6
            ZbvknyS+hI4WpIKXy08aHkpoCvvGQoqfinAwYHFGJYRveTfz6e6C7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T21:12:37Z"
    mac: ENC[AES256_GCM,data:IWHFK2osyIi1xukoU9U19Zjw46gvfue6ApNIbYKDE4egkgJ3kY8+QyCe9oLXPkjBzUmfux4IVlsJ6/ZEruVx3M1PPFYnn9Dy3xnTKQy3ayATife669j5lN0Y/QFtBF+Tg9kWZGI3myWWtlT625jEFi8BmJJk0SsoHCBxyGHfR3k=,iv:5wOgqkgy32PLXjOVCPSzt2BRYdTTqZ1g2TofGOViwbc=,tag:p1GKhVt66q0rsDAPwHXH3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
