
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: gdd-service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: HOMEPAGE_VAR_SONARR_TOKEN
    remoteRef:
      key: "f5a6a538-d353-4194-8006-b21d0188b04c"
  - secretKey: HOMEPAGE_VAR_TANDOOR_TOKEN
    remoteRef:
      key: "9a48b0fb-72d4-497d-969b-b39c015bdce3"
  - secretKey: HOMEPAGE_VAR_JELLYSTAT_TOKEN
    remoteRef:
      key: "ebbdb478-2e2f-4f2e-9b17-b39c016ff3e5"
  - secretKey: HOMEPAGE_VAR_JELLYSEERR_TOKEN
    remoteRef:
      key: "f2d931a8-613e-410d-86a9-b39c0170673d"
  - secretKey: HOMEPAGE_VAR_JELLYFIN_TOKEN
    remoteRef:
      key: "322eef18-59cc-45d5-a4c6-b39c01707a2a"
  - secretKey: HOMEPAGE_VAR_lidarr_API_KEY
    remoteRef:
      key: "46e906de-7212-4403-b00f-b4a9014da1de"
  - secretKey: HOMEPAGE_VAR_prowlarr_API_KEY
    remoteRef:
      key: "cf85a113-53c6-4dcf-8b41-b21f00617e1f"
  - secretKey: HOMEPAGE_VAR_radarr_API_KEY
    remoteRef:
      key: "e7327e8d-ba77-43e3-8e49-b4a9014dd067"
  - secretKey: HOMEPAGE_VAR_IMMICH_TOKEN
    remoteRef:
      key: "6bb2875d-32b5-40aa-bfdc-b4a9014de3bf"
#  - secretKey: HOMEPAGE_VAR_NEXTCLOUD_TOKEN
#    remoteRef:
#      key: "<bitwarden-item-id>"
#  - secretKey: HOMEPAGE_VAR_PAPERLESS_TOKEN
#    remoteRef:
#      key: "<bitwarden-item-id>"
#  - secretKey: HOMEPAGE_VAR_GRAFANA_USER
#      key: "<bitwarden-item-id>"
#  - secretKey: HOMEPAGE_VAR_GRAFANA_PASS
#    remoteRef:
#      key: "<bitwarden-item-id>"
#  - secretKey: HOMEPAGE_VAR_HOMEASSISTANT_TOKEN
#    remoteRef:
#      key: "<bitwarden-item-id>"
#  - secretKey: HOMEPAGE_VAR_CALIBREWEB_USER
#    remoteRef:
#      key: "<bitwarden-item-id>"
#  - secretKey: HOMEPAGE_VAR_CALIBREWEB_PASS
#    remoteRef:
#      key: "<bitwarden-item-id>"
#  - secretKey: HOMEPAGE_VAR_FORGEJO_TOKEN
#    remoteRef:
#      key: "<bitwarden-item-id>"
  - secretKey: HOMEPAGE_VAR_AUTHENTIK_TOKEN
    remoteRef:
      key: "4ca45515-79bc-44fb-8e78-b39c00584b45"

