# yaml-language-server: $schema=http://frigate.int.gddnet.io/api/config/schema.json
---
logger:
  default: info
  # logs:
  #   frigate.record: debug

mqtt:
  host: emqx.default.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous


snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7

record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 2
      mode: active_objects

objects:
  track:
    - person
    - cameras
    - dog
    - cat


go2rtc:
  streams:

    frigate_garage_hq: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.0.60.119:554/cam/realmonitor?channel=1&subtype=0
    frigate_garage_lq: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.0.60.119:554/cam/realmonitor?channel=1&subtype=1
    frigate_frontporch_hq: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.0.50.110:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
    frigate_frontporch_lq: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.0.50.110:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
    frigate_driveway_hq: rtsp://10.0.60.53:554/11
    frigate_driveway_lq: rtsp://10.0.60.53:554/11
    frigate_spa_hq: rtsp://10.0.60.88:554/1/h264major
    frigate_spa_lq: rtsp://10.0.60.88:554/1/h264major
    frigate_front_hq: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.0.60.25:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    frigate_front_lq: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.0.60.25:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1

cameras:

  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_garage_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_garage_hq
          roles: ["record"]


  frontporch:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_frontporch_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_frontporch_hq
          roles: ["record"]

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_driveway_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_driveway_hq
          roles: ["record"]

  spa:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_spa_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_spa_hq
          roles: ["record"]

  front:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_front_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_front_hq
          roles: ["record"]

 