---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-reporter-ui
  annotations:
    tailscale.com/proxy-group: ts-ingress
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Observability
    gethomepage.dev/name: Policy Reporter
    gethomepage.dev/icon: mdi-shield-check
    gethomepage.dev/description: "Tailscale only | Kyverno policy reports"
    gethomepage.dev/siteMonitor: "http://policy-reporter-ui.kyverno.svc:8080"
spec:
  ingressClassName: tailscale
  rules:
    - host: kyverno.barn-walleye.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: policy-reporter-ui
                port:
                  number: 8080
  tls:
    - hosts:
        - kyverno.barn-walleye.ts.net
