# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: pangolin-operator-credentials
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:Ym+LfBTnGnTAfenQ5LoIxWmYYAu7b6tXcaw=,iv:FdStIFdVp8TDHwragREcgunnrrA5IVuorAAOlLGnbLw=,tag:FcsB1TzcE93EEa1ew/NWYw==,type:str]
    PANGOLIN_API_URL: ENC[AES256_GCM,data:fZAaJkdWJhgSCmN3gc3NHqQkFDPymN520hI=,iv:ZkKo8cm14kxSO/GAm6NGSdz6xtkatDcKzW9nSMI5A6A=,tag:bSp/9f9XjpkvOq5HIXdHwA==,type:str]
    PANGOLIN_API_KEY: ENC[AES256_GCM,data:zAxeWvnu5j48XLaCc6AZOOIAenZMZDKWEZsbSUawVUvsnMDo5g+VqDTQ9mKh6Tivx13vkd9KF/Q=,iv:FCvhyEgAleI8bcVK6sgNh8QJr7417DxW5Nde7qcwqtc=,tag:czGmpfIVQ+EEJVNfO2Py9A==,type:str]
    PANGOLIN_ORG_ID: ENC[AES256_GCM,data:wz+qQU+1,iv:A/xoS/QuElWE3muuDHD31cSTXKc7ChaUa6eopub5Snc=,tag:iCEVJzSzscLJaNqxU6Wmsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TVY0MEoybU1zYnZhbEhH
            NE5LbG1RTjZFbzRsaWpPaDFUeGU2SzNvaUZJCnE5MTF2cjZWZ0x6S0hLZWp6alVx
            MHRkU21nUi9wUitOeFR2SHpEZnVMS1EKLS0tIEViU0lUd0syTDdWdERUZUIwZVlr
            aGljdzdBL0cwV081NG1zUzk2cUFQbncKoD7A47wgqwtxMEYnYIIk9gzlJrpj8Q7q
            I7Xss2wjQPrrbPL7Qc3dTxPfB/natv7eOIUMARPm8+0JedCMJ5FHqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T06:05:48Z"
    mac: ENC[AES256_GCM,data:tUNn0nhE4qpTqP6GatQs+B0WiMMo2DY5kpchD0uiHX85HAqluGGVsg5PzlelbNzYY2TcO3YZaSBVil6f187mEt96hFdE0xL+Y9Th/dZmoycCvixYrV7IM0A/C8ozGQ6TUXUIbubOCW6KMyGIENTUyoLi0K8CLHVo1QP2uq04nwM=,iv:kBnvVbh98yLSkXGLwNYn+SGZTiK0NN6896DWJbHrseA=,tag:kueox7pderTL6ZklpYZC9w==,type:str]
    version: 3.13.3
