# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: pangolin-operator-credentials
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:izqIYvSkPqdThW1fT7TG8IQaG5MSiLoTZEw=,iv:Nu7p8PSNA/ZVqjMG/Go9I3PzkZMQwm342/aWBMAeca0=,tag:ylxGaZVTUYdHod02vp6x9A==,type:str]
    PANGOLIN_API_URL: ENC[AES256_GCM,data:6FkORHBFssCSavz2KpKKm/1ruCukMYYLhKY=,iv:BT7+mM4S6jlFjwfy1MgAF/K/zEOkN3FsCmdKlVvJ1WQ=,tag:dSX83vWL7HC4zI5qSJye6Q==,type:str]
    PANGOLIN_API_KEY: ENC[AES256_GCM,data:GpTowEVC9D249Hw6//n97gnvJD9Da3R8aA6Tg8eIqWn0TF3l/2Gh97GY1OxIaKF6OpUZhQGQZHg=,iv:O4hxgcSYxg69/CuVZLlmRH2YjJlR8YQ6kdtEPefShZg=,tag:D1G6fYd1DI23qX3RrtMTTQ==,type:str]
    PANGOLIN_ORG_ID: ENC[AES256_GCM,data:xFYqsUN7,iv:yVXWqXdu2eFbFVh8/OxJTtYoGJnx/8tNiSb155GBE3g=,tag:CbTrnvsB5RKYZ5wl4b4mQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYUNRM05FclVNV0V0NFpD
            Ym9TQ0NsYjlTWWtVQUczQXUrMlluVC92aFUwCnZwZmFpYlVnM3h6REdCVVlpUmpk
            RVVxYVR6NHkweXhIdkJYa0pneTQxTkkKLS0tIFpONnhYOGZackRFdXZvNDR4QUFE
            MDlzQUpBRHdma1lsbFFBSGRNbFlrNWMKwoH2WcN3zHStL5fqMlqCS7VU3gwsS2W1
            4wx5rZqcaOFg2J72Ih+m6b29gLxZUVdJa7CfNHXtQGrwijHNCiSLwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T22:34:26Z"
    mac: ENC[AES256_GCM,data:Zxpoq+q62GcVDoNitKHMJdpviKs3MBUtwQZYmjN8hOSqPricwOp7q45fXhWvcz4xUgtZtOyvtKzA6DJArcBB0L80acfqu0wz74/dJI7/B8jBEmPR6lOYO9Cj/dP2hwG8GBEmLWDeFelRgr3218i13fAVS0Xt+p7CXniTgsp4pJY=,iv:UZoWdsEwGKAWrJyXemR26s4J83juFtTIJyLPKj8XjZc=,tag:ijMKYgQeuD2z6bC8j/Xmmw==,type:str]
    version: 3.13.3
