# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: pangolin-operator-credentials
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:47Hxr0ESQfkK7UhTNtAUFnNhtXqdZy0BWNU=,iv:S9OJZQgw2c7sUU+j4aikjtiiI3NApLrfqXXy0E5wld4=,tag:gaaksJKHBXB5Fj9K/ZJYeA==,type:str]
    PANGOLIN_API_URL: ENC[AES256_GCM,data:WXsg/6cbGhXrfFwl5elIgUpPb4eaUih9w1IfTtlL,iv:4ajPZWBp5wPwcTniNLVCBDfUlhbpRPGf68XFUw+lWgo=,tag:3kNDiZDM6EDnIqHVcKLL8g==,type:str]
    PANGOLIN_API_KEY: ENC[AES256_GCM,data:9UN0IOrqMpLt/vCNW8EmQqbVLmvGefoPEBLyOlutSIvrgZo1Yly9/PVmXvx2fMdKy6jYseFFN10=,iv:hXCW8zwQsUgqOlZEwHC1SBUWxm2uIFapfuI0vrFLsPE=,tag:djpLTSXRUJDEuwM9PiYH1Q==,type:str]
    PANGOLIN_ORG_ID: ENC[AES256_GCM,data:pUcEDYIh,iv:l2ml9wkqLQkbe5DADTw2z5MglW/MYn2FUm+GWopy9ug=,tag:TdZ1f0hwh9dNDF+0QR9UZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbFVKc0o2MFlHZU55Zzlh
            ZjFhYXlVZFdxRStuc1Jtanc0dXlBNmgrNUNnCjg4UkRjR2ZpQmRITDMyeGZxT3Ro
            Z0c5U3JrSTd2elV2clhzazZ3T284SzAKLS0tIFFaRFFKa3ZCOFVnOG0vYWc3S01s
            WVNnaVpXa1VtUlpZeDZHMXJuUHBpV28KzVkI1EpObJYftAlCaGqvjnIDpY3/kRBy
            o1lQeeh6jPpp6KP1n1IvOayQMxRl/CnF+LvMRdu6Ty85oxPHncV5fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T00:32:40Z"
    mac: ENC[AES256_GCM,data:VcdpMzKAYpxmdTUHKSZyK9IOJl6XmZJPqKSnm92VSJL7KYPV8rcv8/y12uLxaIc1zEdv7/sgraOQHKStBXS8U3pta90fHUTaJ3/brlDp7DyaQiuaaVoa84g7JUeqk5b01xsBpGkIr3NypA93TrbFFjU5XqyORbuUZ8eK9t/5Zbk=,iv:InaqJAeK6oUhbht2PV8Sd47dschPrtAEdYV/rVBRzTM=,tag:ztSjnHd1YZPn9KFD0B/gPg==,type:str]
    version: 3.13.3
