---
# Email credentials for notifications
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-email-secret
  namespace: gdd-social
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: synapse-email-secret
    creationPolicy: Owner
  data:
    - secretKey: smtp_user
      remoteRef:
        key: "TODO-BITWARDEN-UUID-FOR-SMTP-USER"  # TODO: Create in Bitwarden
    - secretKey: smtp_pass
      remoteRef:
        key: "TODO-BITWARDEN-UUID-FOR-SMTP-PASS"  # TODO: Create in Bitwarden
