
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: booklore-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: DATABASE_USERNAME
    remoteRef:
      key: "835eebb9-ab8d-42ca-87f1-b2de01514044"
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: "0465fdf0-ce71-460a-9b18-b2de015156bc"


