apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-app
  namespace: service
  labels:
    homelab/usage: service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-books
  namespace: service
  labels:
    homelab/usage: service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
---