---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dcs-server-secret
  namespace: gdd-game
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: "9920a731-e663-4c35-b18b-b22801322a0e"
