---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dcs-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  timeout: 2h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      dcs-server:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/aterfax/dcs-world-dedicated-server
              tag: latest
            env:
              TZ: America/Chicago
              PUID: "1000"
              PGID: "1000"
              DCSAUTOINSTALL: "1"
              DCSMODULES: "SYRIA_terrain MARIANAISLANDS_terrain"
              FORCEREINSTALL: "0"
              AUTOSTART: "0"
              TIMEOUT: "30"
              ENABLE_DCS_RETRIBUTION: "1"
              DOCKER_MODS: "aterfax/dcs-world-dedicated-server-mod-retribution:latest|aterfax/dcs-world-dedicated-server-mod-dcsserverbot:latest"
              DCSSBAUTOINSTALL: "1"
              DCSSBAUTOSTART: "0"
            envFrom:
              - secretRef:
                  name: dcs-server-secret
            ports:
              - containerPort: 3000
                hostPort: 3000
                protocol: TCP
              - containerPort: 3001
                hostPort: 3001
                protocol: TCP
              - containerPort: 10308
                hostPort: 10308
                protocol: TCP
              - containerPort: 10308
                hostPort: 10308
                protocol: UDP
              - containerPort: 10309
                hostPort: 10309
                protocol: TCP
              - containerPort: 10309
                hostPort: 10309
                protocol: UDP
              - containerPort: 8088
                hostPort: 8088
                protocol: TCP
              - containerPort: 42674
                hostPort: 42674
                protocol: TCP
              - containerPort: 42675
                hostPort: 42675
                protocol: TCP
              - containerPort: 5002
                hostPort: 5002
                protocol: TCP
              - containerPort: 5002
                hostPort: 5002
                protocol: UDP
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                drop: []
            resources:
              requests:
                cpu: 500m
                memory: 4Gi
              limits:
                memory: 16Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
#        seccompProfile: { type: Unconfined }
      nodeSelector:
        kubernetes.io/hostname: gddnet-w9
    service:
      app:
        ports:
          webtop:
            port: 3000
    persistence:
      config:
        existingClaim: dcs-server-config
        globalMounts:
          - path: /config
