
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperleess-secret
  namespace: service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: PAPERLESS_ADMIN_USER
    remoteRef:
      key: "ee5a71df-a12b-4693-a59b-b22d015e84dc"
  - secretKey: PAPERLESS_ADMIN_PASSWORD
    remoteRef:
      key: "2eb395e3-0cf6-4f14-9765-b22d015ea086"
  - secretKey: PAPERLESS_SECRET_KEY
    remoteRef:
      key: "be07b6a1-9e16-4e95-a551-b22d015ed715"
