---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            supplementalGroups:
              - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.14.7
            env:
              # Configure application
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SECRET_KEY
              PAPERLESS_URL: https://paperless.int.gddnet.io
              PAPERLESS_PORT: "8000"
              PAPERLESS_TIME_ZONE: "America/Chicago"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              # Configure folders
              PAPERLESS_CONSUMPTION_DIR: /mnt/media/incoming
              PAPERLESS_DATA_DIR: /data/local/data
              PAPERLESS_EXPORT_DIR: /mnt/media/incoming
              PAPERLESS_MEDIA_ROOT: /data/local/media
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGES: nld
              PAPERLESS_OCR_LANGUAGE: nld
              # Configure redis integration
              PAPERLESS_REDIS: redis://dragonfly.database.svc.cluster.local:6379
              # Configure user permissions
              USERMAP_GID: "65542" # gladius:external-services
              # Configure admin user
              PAPERLESS_ADMIN_USER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_USER
              PAPERLESS_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_PASSWORD
              PAPERLESS_APPS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_APPS
              PAPERLESS_SOCIALACCOUNT_PROVIDERS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SOCIALACCOUNT_PROVIDERS
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 2Gi
              limits:
                memory: 6Gi



    service:
      app:
        controller: paperless
        ports:
          http:
            port: 8000


    ingress:
      app:
        className: "internal"
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.gddnet.io
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Service
          gethomepage.dev/name: Paperless
          gethomepage.dev/icon: paperless.png
        hosts:
          - host: paperless.int.gddnet.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: paperless-data
        advancedMounts:
          paperless:
            app:
              - path: /data/local
