
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbit-secret
  namespace: plex
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: WIREGUARD_ENDPOINT_IP
    remoteRef:
      key: "50d4b2b5-7101-4acb-9c61-b21b015dce1d"
  - secretKey: WIREGUARD_PUBLIC_KEY
    remoteRef:
      key: "d5bd794f-15c4-4b1c-aee8-b21b015de2a6"
  - secretKey: WIREGUARD_PRIVATE_KEY
    remoteRef:
      key: "a0995b11-56e0-46d0-a917-b21b015df88a"
  - secretKey: WIREGUARD_ADDRESSES
    remoteRef:
      key: "d2f6df19-2272-4629-ac48-b21b015e0e9d"


