---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbit-vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      qbit-vpn:
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.4@sha256:17e3e5f1c7e7fe81434f9d1f5f2e00da9a67f6dbfda1c988c0619932cb856047
            env:
              TZ: America/Chicago
              # QBITTORRENT__PORT: &port 80
              # QBITTORRENT__BT_PORT: &bittorrentPort 28163
              #QBT_Preferences__WebUI__AlternativeUIEnabled: true
              #QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              #QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
              #  ${CLUSTER_CIDR}, ${NODE_CIDR}, 192.168.0.0/24
              #QBT_Preferences__WebUI__LocalHostAuth: false
              #QBT_Preferences__WebUI__RootFolder: /add-ons/VueTorrent
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 25m
                memory: 1G
              limits:
                memory: 12G

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            env:
              # DOT: "off"
              # DNS_ADDRESS: "127.0.0.2"
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              WIREGUARD_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: &port 8080
              FIREWALL_OUTBOUND_SUBNETS: "10.0.0.0/8"
              VPN_INTERFACE: wg1

            envFrom:
              - secretRef:
                  name: qbit-secret
            securityContext:
              capabilities: { add: ["NET_ADMIN"] }
              allowPrivilegeEscalation: true
              privileged: true

          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: 0.0.4@sha256:838ba41b3c736b23ae30f7e79a2610173f389a5ac6fb2b3e9c7bd482b9353c18
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: *port
      # bittorrent:
      #   controller: *app
      #   type: LoadBalancer
      #   annotations:
      #     io.cilium/lb-ipam-ips: ${SVC_QBITTTORENT_VPN_ADDR:=temp}
      #   ports:
      #     bittorrent:
      #       enabled: true
      #       port: *bittorrentPort
      #       protocol: TCP
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Plex
          gethomepage.dev/name: qBittorrent VPN
          gethomepage.dev/icon: qbittorrent.png
          gethomepage.dev/description: Torrent Client
          gethomepage.dev/widget.type: qbittorrent
          gethomepage.dev/widget.url: http://qbit-vpn.plex:8080
          gethomepage.dev/widget.username: "admin"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_QBIT_TOKEN}}` }}"
          external-dns.alpha.kubernetes.io/target: internal.gddnet.io
        hosts:
          - host: "qbit.int.gddnet.io"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
      add-ons:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /add-ons
      media:
        type: nfs
        server: 10.0.30.134
        path: /medianfs
        globalMounts:
          - path: /mnt/media