---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-b2-volsync
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: VOLSYNC_B2_RESTIC_PASSWORD
    remoteRef:
      key: "ba58f8dc-b191-4224-90a3-b38601425ace"
  - secretKey: VOLSYNC_B2_ACCESS_KEY_ID
    remoteRef:
      key: "0d408eae-142c-4947-ba64-b38601426e3b"
  - secretKey: VOLSYNC_B2_BUCKET_ENDPOINT
    remoteRef:
      key: "4604a62e-9d1c-4655-99c2-b386014285af"
  - secretKey: VOLSYNC_B2_SECRET_ACCESS_KEY
    remoteRef:
      key: "11ce4859-90d2-4501-ac01-b3860142ab16"
  target:
    template:
      engineVersion: v2
      data:
#        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}${NS}/${APP}"
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}/omni-talos-gdd/${NS}/${APP}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"