
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monica-secret
  namespace: gdd-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: DONETICK_OAUTH_CLIENTID
    remoteRef:
      key: "8348a9be-9771-4df1-bbf8-b365006fbfd0"


