---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator
  namespace: network
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: client_id
    remoteRef:
      key: "afd19ba8-85bc-4ca5-97fd-b2dd0153d9f1"
  - secretKey: client_secret
    remoteRef:
      key: "d5195195-b5e5-42a2-b3fd-b2dd0153ef63"





