---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-ingress
spec:
  type: ingress
  replicas: 3
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-kube
spec:
  type: kube-apiserver
  replicas: 3
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: connector
  namespace: network
spec:
  tags:
    - "tag:connector"

  appConnector:
    routes:
      - 10.0.10.0/24
      - 10.0.30.0/24
      - 10.0.31.0/24
      - 10.0.50.0/24
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: connector-pdb
  namespace: network
spec:
  minAvailable: 1
  selector:
    matchLabels:
      tailscale.com/parent-resource: connector
      tailscale.com/parent-resource-type: connector
