---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app boundary
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      boundary:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: hashicorp/boundary-enterprise
              tag: 0.19.3-ent
            command:
              - boundary 
              - server
              - -config=/boundary-hcp-worker/config/config.hcl

            env:
              TZ: America/Chicago

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512M

    service:
      app:
        controller: boundary
        externalTrafficPolicy: Cluster
        type: LoadBalancer
        ports:
          http:
            port: 9202


    persistence:
      data:
        existingClaim: boundary-data
        advancedMounts:
          boundary:
            logs:
              - path: /boundary-hcp-worker/logs
            file:
              - path: /boundary-hcp-worker/file
            recording:
              - path: /boundary-hcp-worker/recording
      config:
        enabled: true
        type: configMap
        name: boundary-config
        globalMounts:
          - subPath: config.hcl
            path: /boundary-hcp-worker/config/config.hcl
