apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boundary-data
  namespace: security
  labels:
    homelab/usage: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
---