---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vector-aggregator
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      vector-aggregator:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"


        containers:
          app:
            image:
              repository: docker.io/timberio/vector
              tag: 0.50.0-alpine@sha256:93761c26fa3a3793f5f200de0f4cfc6102b5e9803ab33b4830d0873ba8dbdc4f
            args: ["--config", "/etc/vector/vector.yaml"]
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    service:
      app:
        controller: vector-aggregator
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: vector.int.gddnet.io
          lbipam.cilium.io/ips: 10.0.32.50
        ports:
          http:
            primary: true
            port: 8686
          journald:
            port: 6000
          kubernetes:
            port: 6010
          vyos:
            port: 6020
    persistence:
      config:
        type: configMap
        name: vector-aggregator-configmap
        globalMounts:
          - path: /etc/vector/vector.yaml
            subPath: vector.yaml
            readOnly: true
      data:
        type: emptyDir
        globalMounts:
          - path: /vector-data-dir

