---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dbbeaver
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
  values:
    controllers:
      dbbeaver:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: dbeaver/cloudbeaver
              tag: 25.1.5
            env:
              HTTP_PORT: &port 8978
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 500Mi
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: ceph-block
        size: 100Mi
        globalMounts:
          - path: /opt/cloudbeaver/workspace
