---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dbeaver
  namespace: database
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      dbeaver:
        type: statefulset
        annotations:
          
        containers:
          app:
            image:
              repository: dbeaver/cloudbeaver
              tag: 25.1.4
            env:
              TZ: America/Chicago

            securityContext:
              {}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 300Mi
    service:
      app:
        controller: dbeaver
        ports:
          http:
            port: 8978
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/name: Dbeaver
          gethomepage.dev/icon: cloudbeaver.svg

        hosts:
          - host: dbeaver.int.gddnet.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 500Mi
        globalMounts:
          - path: /opt/cloudbeaver/workspace
