---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dbeaver
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
  values:
    controllers:
      dbeaver:
        type: statefulset
        annotations:

        containers:
          app:
            image:
              repository: dbeaver/cloudbeaver
              tag: 25.1.5
            env:
              TZ: America/Chicago

            securityContext:
              {}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 300Mi
    service:
      app:
        controller: dbeaver
        ports:
          http:
            port: 8978

