---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
spec:
  interval: 30m
  url: https://charts.goauthentik.io/
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2025.8.4
      sourceRef:
        kind: HelmRepository
        name: authentik
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:

      deploymentStrategy:
        type: RollingUpdate
      env:
        TZ: America/Chicago

    authentik:
      redis:
        host: dragonfly.database.svc.cluster.local
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)
    server:
      replicas: 1
      pdb:
        enabled: true
        minAvailable: 1
        maxUnavailable: 1

      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 2Gi

    route:
      app:
        hostnames:
          - sso.gddnet.io
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
            - identifier: app
              port: 9443
    prometheus:
      rules:
        enabled: true
    postgresql:
      enabled: false
    redis:
      enabled: false