---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2025.8.4
      sourceRef:
        kind: HelmRepository
        name: authentik
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      env:
        TZ: America/Chicago
      envFrom:
        - secretRef:
            name: *secret
    authentik:
      redis:
        host: dragonfly.database.svc.cluster.local
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)
    server:
      replicas: 1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    worker:
      replicas: 2
    route:
      app:
        hostnames:
          - sso.gddnet.io
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
            - identifier: app
              port: 9443
    prometheus:
      rules:
        enabled: true
    postgresql:
      enabled: false
    redis:
      enabled: false