---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 5m


  values:
    metrics:
      enabled: true
    service:
      enabled: true

    server:
      ingress:
        enabled: true
        ingressClassName: external
        activeService: true
        pathType: Prefix
        annotations:
          external-dns.alpha.kubernetes.io/target: external.gddnet.io
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Security
          gethomepage.dev/name: Vault
          gethomepage.dev/icon: vault.png
        hosts:
          - host: &host vault.gddnet.io
            paths: []

      extraLabels:
        configmap.reloader.stakater.com/reload: vault-config
      dataStorage:
        enabled: true
        storageClass: "ceph-block"
        size: 5Gi
      extraEnvironmentVars:
        TZ: America/Chicago
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
      standalone:
        enabled: false
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              telemetry {
                unauthenticated_metrics_access = "true"
              }
            }
            storage "raft" {
              path = "/vault/data"
            }

            service_registration "kubernetes" {}
      statefulSet:
        securityContext:
          pod:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
          container:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - "ALL"
    ui:
      enabled: true
      serviceType: "ClusterIP"