apiVersion: v1
kind: Secret
metadata:
    name: meeplestats-mongo
stringData:
    MONGO_INITDB_DATABASE: ENC[AES256_GCM,data:h1/rLaYmD6j/k54=,iv:Hz6gSwIokPFGBnFqzO1S8xHmvehAFjELyY1BdHhTfkE=,tag:VrDhWFkGapcCDZ6s4vzDZg==,type:str]
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:8VTDyA==,iv:Q5IbZI5Nm4eHnhuq8zK4yrxS4K1QPZlIu0RqXC7zPXA=,tag:ZMvUKUh2qcQiD56j7XAu+g==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:fU9+2fjgB7UhFfJxQSAsf/PvEYx55Ub75QNfB2mlfZgy/0V+xwfso3AQiGzKWJAR,iv:JSdvTCb6Fa6g5zscKJ6qaL9BtvVmD3IlxfK3ZPhncMM=,tag:bSa8bFl4JkWJtM8g3t0Npw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcVcxNDNxSWVJVGtyZjN6
            TlJoeEN2aTE3ZnpLU2VhTXlnSkVWeTU2Ym1RCkJIL2xQaktzZkpqZDkyUjRYVFVz
            VjV1TDcwVWNPb1VZbGdHQzNwSzRkWTAKLS0tIFROaGhaZGxyR0d2TmxEaHRvaUE3
            SmJRYitaeWtnM0sxd1RVU0UyVlVKZWMKnGr+NE42CyFsTqRmUjxBvkZTAO+Hnpg6
            yCe5Xq3N39MFEKDs6sBdKO43fdYenNHMI6Ngi9G6xh2PkjpmjtuVvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T01:00:13Z"
    mac: ENC[AES256_GCM,data:fbkl/Cjc3H2KvBf3H796HXOSEXtToaFKw8a19JPthn9O+S4nFtm4em2J4+F2ha1Akls367MH1qLIH4B6HTCuFo7m1qv/1jygAlihdi3Bf6OpKBYi+KStiiQunJ6XPrL2U2H1ySHyaK4DHutRZK4hXyZwMAR/sMxBjF7ldfZ1zo8=,iv:zucoXcKmryhhPgf5HHylH9Lr/Giu6aYo2hzHO6Ofo3Y=,tag:c0voBbY//hMM0n6rhENDRA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: meeplestats-backend
stringData:
    MONGO_URI: ENC[AES256_GCM,data:pwAAleTDhoc73V+B5pNEVV3NkjZ8kS/PNavUHyaCIDbONlZih1wGkm0KKowNK+FcefGVB/xkKMx4HBKLGCHLZQivaarGIoxjTQZ7GNjHq5Nxn+SyFMspcGHUWV+khk1rfrsJ6D8DfqKXg6pK,iv:fVzNaxTrTWBo4WzpTGsizz4X9G8sm8cuOHxksTdiBF0=,tag:573Vq76++urtgMgzgZBBEg==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:B8ZOKc3oegwcbADk3YQ4Sr8ZOji9PfHUr5m9xw1lw1qft3E1bqfUcHxojSc=,iv:abNxxVFCoEXhhf0+GaQfHeYuZ4AkxrkkRC1W5+3Wd1g=,tag:+pZFFQ6iWtwcmUDSBD3E4g==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:K9h2rKufSsonaIVS/z6nziHuikTwcYvpdYzxTUWKwL7noudo52ExXd4AjK4=,iv:5onwsxtUp69kf066R3xUukVozqvaiEc0f/2P696L1Po=,tag:J6hocNwdtg/eUFw5uXfYyg==,type:str]
    BGG_USERNAME: ENC[AES256_GCM,data:qd1M9UIC81k=,iv:gCN2xvyuMsV/Q846OdNpZfDkHLX7rv2Q5e6vSTWGxgY=,tag:96pE4khhbxAz/G+qrA03Tg==,type:str]
    BGG_API_KEY: ENC[AES256_GCM,data:UKEvaHUMAbA=,iv:q1vl+y9eG4Sc1EBjhFtlXKzQhHvfZehc0UZ4n2idGr0=,tag:78+jr+4LlrX4U1szGwK5vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcVcxNDNxSWVJVGtyZjN6
            TlJoeEN2aTE3ZnpLU2VhTXlnSkVWeTU2Ym1RCkJIL2xQaktzZkpqZDkyUjRYVFVz
            VjV1TDcwVWNPb1VZbGdHQzNwSzRkWTAKLS0tIFROaGhaZGxyR0d2TmxEaHRvaUE3
            SmJRYitaeWtnM0sxd1RVU0UyVlVKZWMKnGr+NE42CyFsTqRmUjxBvkZTAO+Hnpg6
            yCe5Xq3N39MFEKDs6sBdKO43fdYenNHMI6Ngi9G6xh2PkjpmjtuVvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T01:00:13Z"
    mac: ENC[AES256_GCM,data:fbkl/Cjc3H2KvBf3H796HXOSEXtToaFKw8a19JPthn9O+S4nFtm4em2J4+F2ha1Akls367MH1qLIH4B6HTCuFo7m1qv/1jygAlihdi3Bf6OpKBYi+KStiiQunJ6XPrL2U2H1ySHyaK4DHutRZK4hXyZwMAR/sMxBjF7ldfZ1zo8=,iv:zucoXcKmryhhPgf5HHylH9Lr/Giu6aYo2hzHO6Ofo3Y=,tag:c0voBbY//hMM0n6rhENDRA==,type:str]
    version: 3.13.3
