---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: govee2mqtt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      govee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/wez/govee2mqtt
              tag: 2026.03.25-ab9deb66@sha256:a9d9fe330574d16be5a68175f2572615f9e55385695ab40652cc388076a07643
            env:
              TZ: America/Chicago
              GOVEE_TEMPERATURE_SCALE: F
              GOVEE_LAN_SCAN: "10.0.50.174"
              GOVEE_MQTT_HOST: emqx-listeners.database.svc.cluster.local
              GOVEE_MQTT_PORT: "1883"
              GOVEE_MQTT_USER:
                valueFrom:
                  secretKeyRef:
                    name: govee2mqtt-secret
                    key: GOVEE_MQTT_USER
              GOVEE_MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: govee2mqtt-secret
                    key: GOVEE_MQTT_PASSWORD
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "multus-vlan50",
            "namespace": "network",
            "ips": ["10.0.50.210/24"]
          }]
      nodeSelector:
        kubernetes.io/hostname: gddnet-w9
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 64Mi
        storageClass: ceph-block
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
