# =============================================================================
# !! PLAINTEXT — ENCRYPT WITH SOPS BEFORE `git add` !!
#   sops --age age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y \
#        --encrypt --encrypted-regex '^(data|stringData)$' --in-place \
#        kubernetes/apps/gdd-jarvis/govee2mqtt/app/secret.sops.yaml
# Shared EMQX broker credential also used by zigbee2mqtt/zwave2mqtt.
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: govee2mqtt-secret
stringData:
    GOVEE_MQTT_USER: ENC[AES256_GCM,data:souyY5k=,iv:pw5ikbbXYwNvKM9RabSQ1jDMoLLQxXgbxoSHrM1sILo=,tag:L5DXWD75RRglUaJx9hYF/A==,type:str]
    GOVEE_MQTT_PASSWORD: ENC[AES256_GCM,data:1DyvCgBcCzI=,iv:Bq9KTSuOSjX97bIAEQBPW8wRYIDSKmrJDoQYmc38Lrk=,tag:9P4wL1II+K/xgSZykZwHSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV3NVTzFFc0xFV1FKR1g2
            MnNoaitDalNUWmc5ay9DYStnbVlqRDJhOGhJCk9MM3YrdlpWOFRXZmRiUVBlWGxu
            N2xSVHEvbWxyb3lJcEl5WDBpMGFETTgKLS0tIFUxay9MeEd1bTV4VzVYK0l3U0FR
            UTFFMXVZK2tKcERpdm01UFd1Y242ZG8K0LZxLZXOJQWWsqYu1tkk/ldedjfTnsPq
            59YLM4KcBkISzWaMxLYrpkihnmWjL+MyMYKOv9uyCUVJ/d0hvSAfYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T20:14:36Z"
    mac: ENC[AES256_GCM,data:DaoF0q2YfMNu57ILDBjbpn0eQtU+17T1UOZz7obPKvAiImUio/dKyLtULlePRkuE6rmmz3WR+dlL6SnauRSJDI4hN/cqu6gVKaqgZ0L6dg9kUWaMq3UuDWcNXy7FUkdvy7QxIKzuRm5BN/Ed7NiYUgPwaowPXtRKwALosets1Dw=,iv:SI8LCUjsQxLzMP4zG7dxf1T11EWKHU/Jnimj8NfGFVA=,tag:zCfNnklm8iFXqP8eSFwlIA==,type:str]
    version: 3.13.3
