---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: musicseerr
  annotations:
    tailscale.com/proxy-group: ts-ingress
spec:
  ingressClassName: tailscale
  rules:
    - host: musicseerr.barn-walleye.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musicseerr
                port:
                  number: 8688
  tls:
    - hosts:
        - musicseerr.barn-walleye.ts.net
