---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: collabora-admin-password
  namespace: gdd-service
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: collabora-secret
  namespace: gdd-service
spec:
  refreshInterval: 12h
  target:
    name: collabora-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .password | toString }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: collabora-admin-password
