---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-manyfold
  namespace: flux-system
spec:
  path: ./kubernetes/apps/service/manyfold/app
  targetNamespace: service
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname manyfold
  prune: true
  wait: false
  interval: 10m
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: manyfold.int.gddnet.io
