---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./netpol.yaml
configMapGenerator:
  - name: ntfy-config
    files:
      - config/server.yml
configurations:
  - kustomizeconfig.yaml