# =============================================================================
# !! PLAINTEXT — ENCRYPT WITH SOPS BEFORE `git add` !!
#   sops --age age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y \
#        --encrypt --encrypted-regex '^(data|stringData)$' --in-place \
#        kubernetes/apps/gdd-service/ntfy/app/secret.sops.yaml
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
stringData:
    NTFY_WEB_PUSH_PRIVATE_KEY: ENC[AES256_GCM,data:uI+Hcuc0OpGSJiLSacdYC7pYZS0wlqAAojkSMqozRv3N1qlU3NH0P5AibQ==,iv:VEyl3nvpF9RBVBmrRkZfFQXiQtCViRPSeFB8G4w/5CM=,tag:DnaOOvZHyzZh7RleqS4dow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQzVZRzJBdU1CYTdMc1o5
            OVpTbDd3YUJRdW5DbWZZeUpneUNTZW83dEdBCmR0UXQwenNoZVZwMU1oNEFlOFQ0
            c1BGWUY2UjVWNEdXNks1OFhOU2JCaU0KLS0tIFF4eXlNVjNMMStIU3Y4Q1dxaHZa
            NksvRzhkWS9aWi9EUEF5aFpObmhUcTgKCz+FpzwSLl3rRjsRppcBcmwrgdx4+ScU
            NJ2akTkYoRDtbUHbBmiT1W1Ee0c88kgaT/MFys/fyZ3mk1OT0b2Qwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T06:18:26Z"
    mac: ENC[AES256_GCM,data:TnPvOM6NgNuLBJSm9UC7rkXXdFKVARcAdMDsjS60FORQp2pVSStRlPWlGGFXFIIhWSD9sHIzi5gN30BOlKgOb0swQC2xaXHbD30yyq4jickcCRQuBjRLuF9Pg5Z94N2JBW5ia0xOrEdclzHfWALQQ2hMmGdznQuDKwaK8WUWXtQ=,iv:NYHJIx2TO9mo6s2L7HXUjyaq/1MFXiCFBTTOKMAByyA=,tag:13zIc77nBAPe/jPVEW4avA==,type:str]
    version: 3.13.3
