---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/netbird.io/group_v1alpha1.json
apiVersion: netbird.io/v1alpha1
kind: Group
metadata:
  name: meshmonitor-peers
spec:
  name: meshmonitor-peers
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/netbird.io/networkresource_v1alpha1.json
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: meshmonitor
spec:
  networkRouterRef:
    name: homeops
    namespace: network
  serviceRef:
    name: meshmonitor
  groups:
    - name: tier-admin
