---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: flux-system
spec:
  targetNamespace: &ns jarvis
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  path: ./kubernetes/apps/jarvis/homeassistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      NS: *ns
      GATUS_SUBDOMAIN: jarvis
      VOLSYNC_CAPACITY: 5Gi
