
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
  namespace: plex
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: PROWLARR__POSTGRES__PASSWORD
    remoteRef:
      key: "a4529a4f-0ab6-4f85-922c-b21b013533ac"
#  - secretKey: PROWLARR__AUTH__APIKEY
#    remoteRef:
#      key: "4b4b07dc-b22c-48a6-b50c-b21b01354976"


