---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/common
resources:
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./tailscale-operator/ks.yaml
  - ./securitylab-tunnel/ks.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
        name: not-used
    target:
      kind: Namespace
